### ISSUE TITLE
query parameter for vrf and network does not provide information

### ISSUE THREAD

**Issue by qsnyder** [CiscoDevNet/ansible-dcnm#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible 2.10.10
collection version 1.2.1

### DCNM version

* V 11.5.1

### Affected module(s)

* dcnm_vrf
* dcnm_module

### Ansible Playbook

```yaml
---

- hosts: dcnm_controllers
  gather_facts: false

  vars:
    fabric: DevNet_Fabric

  tasks:
    - name: Query VRF deployed from Ansible
      cisco.dcnm.dcnm_vrf:
        fabric: "{{ fabric }}"
        state: query
        config:
        - vrf_name: Ansible_VRF
          vrf_template: Default_VRF_Universal
          vrf_extension_template: Default_VRF_Extension_Universal
```

### Expected Behavior

I'd expect something querying the specific URI for the VRF or network and returning the configured parameters of such.  Similar to this returned from `/top-down/fabrics/{fabric}/vrfs/{vrf-name}`

```
{
  "fabric": "DevNet_Fabric",
  "vrfName": "Ansible_VRF",
  "vrfTemplate": "Default_VRF_Universal",
  "vrfExtensionTemplate": "Default_VRF_Extension_Universal",
  "vrfTemplateConfig": "{\"advertiseDefaultRouteFlag\":\"true\",\"vrfVlanId\":\"\",\"isRPExternal\":\"false\",\"bgpPassword\":\"\",\"vrfSegmentId\":\"50000\",\"multicastGroup\":\"\",\"configureStaticDefaultRouteFlag\":\"true\",\"advertiseHostRouteFlag\":\"false\",\"trmEnabled\":\"false\",\"trmBGWMSiteEnabled\":\"false\",\"asn\":\"65001\",\"nveId\":\"1\",\"vrfName\":\"Ansible_VRF\"}",
  "tenantName": null,
  "vrfId": 50000,
  "serviceVrfTemplate": null,
  "source": null
}
```

### Actual Behavior

Return looks similar to this

```
ok: [dcnm] => {
    "changed": false,
    "diff": [],
    "invocation": {
        "module_args": {
            "check_mode": false,
            "config": [
                {
                    "vrf_extension_template": "Default_VRF_Extension_Universal",
                    "vrf_name": "Ansible_VRF",
                    "vrf_template": "Default_VRF_Universal"
                }
            ],
            "fabric": "DevNet_Fabric",
            "state": "query"
        }
    },
    "response": []
}
```

The same happens for querying the network, but with the network mentioned.  No details about the VRF/network given.  This is different than other query parameters for modules (such as templates, policy) which actually return information about the item.

### Steps to Reproduce

Run a `query` playbook against a pre-configured network or VRF
