### ISSUE TITLE
Policy Description filed is set to blank when modify policy is used

### ISSUE THREAD

**Issue by risarwarcisco** [CiscoDevNet/ansible-dcnm#139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/risarwar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep 10 2021, 09:13:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

### DCNM version

* V 11.5(3a)

### Affected module(s)

* dcnm_policy

### Ansible Playbook

```yaml
 - name: Configure Mulitple Policies 
        cisco.dcnm.dcnm_policy:
            fabric: "{{ fabric }}"
            deploy: false
            state: merged
            config:
              - switch:
                  - ip: "{{ Switch_name }}"
                    policies:
                        - name: "{{item.policy_id}}"
                          create_additional_policy: false
                          priority: "{{item.priority | default(500)}}"
                          description: "{{item.description}}"
                          policy_vars: "{{ item.Values | default([])}}"
        register: policy_update_data
        loop: "{{ Policies }}"
        ignore_errors: yes
```

### Expected Behavior

I expect this play to update the Policy with specified policy ID and not change fields that have not been changed.

### Actual Behavior

The description field is set to null (when it was previously set upon creation of the policy). Even when the description field is not specified, same result is produced.
