### ISSUE TITLE
Error on Auth with NDFC

### ISSUE THREAD

**Issue by lwy119** [CiscoDevNet/ansible-dcnm#157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

2.11.0

### DCNM version

* ND 2.2(1h) NDFC 12.1.1e

### Affected module(s)

* login (cannot login so i think all resources are affected)
* dcnm_interface (just the one I used)

### Ansible Playbook

```yaml
---

- hosts: dcnm_controllers
  gather_facts: false
  connection: ansible.netcommon.httpapi

  collections:
    - cisco.dcnm

  tasks:
    - name: Query Test
      cisco.dcnm.dcnm_interface:
        fabric: fabric
        state: query
        config:
          - switch:
            - "10.1.1.1"
```

### Debug Output

https://gist.github.com/lwy119/e72960dcda164fb34566dc13d8d511c7

### Expected Behavior

Successfully login and perform the query task

### Actual Behavior

Failed at login step

### Steps to Reproduce

ansible-play -i host query.yml
