### ISSUE TITLE
dcnm_policy state deleted to behave in similar way as state merged

### ISSUE THREAD

**Issue by samurato** [CiscoDevNet/ansible-dcnm#164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Have the dcnm_policy state deleted to behave in a similar way as the state merged.
IN `state:merged`, we can declare `deploy:true or false` and based on that policies are pushed or in pending state for only the targeted switch

### New or Affected modules(s):
cisco.dcnm.dcnm_policy

### DCNM version

* V 11.5(2)

### Potential ansible task config

```yaml
- name: Add LEAF QOS ACL Policy
  cisco.dcnm.dcnm_policy:
    fabric: "{{ targeted_fabric }}"
    state: merged
    deploy: false # Either false or true
    config:
      - name: FREEFORM_QOS_ACL             
      - switch:
          - ip: "{{ ip }}"
  when: switch_role_leaf

```

### References

**Additional context**
`state: deleted` currently deletes the policy and pushes all the pending policies for all switches in the fabric.
https://github.com/CiscoDevNet/ansible-dcnm/issues/163
