### ISSUE TITLE
Support for vlan interfaces to be interacted via dcnm_interface_module

### ISSUE THREAD

**Issue by samurato** [CiscoDevNet/ansible-dcnm#171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected modules(s):

* dcnm__interface_module

### DCNM version

* V 2.1.1

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
name: Replace loopback interfaces
  cisco.dcnm.dcnm_interface:
    fabric: "{{ targeted_fabric }}"
    state: replaced                      
    config:
      - name: Vlan98                                              
        switch:
          - "{{ ip }}"                 # provide the switch where to deploy the config
        deploy: false 
        type: inteface_vlan                    ## choose from [true, false]
        profile:             ## choose from [true, false]
          admin_state: true                ## Routing Tag for the interface
          cmds:                          # Freeform config
            - no ip ospf passive-interface
          description: "^:interlink:L3:UNDERLAY-Inter-Switch:vlan98"
```

### References

Currently I can see SVIs are not supported. 
by Using API tool in DCNM I was able to get the following parameters were pased in JSON file
```json
{
      "serialNumber": "",
      "interfaceType": "INTERFACE_VLAN",
      "ifName": "Vlan98",
      "fabricName": "sam-fabric",
      "nvPairs": {
        "IP": "10.0.2.0",
        "PREFIX": "31",
        "V6IP": "",
        "V6PREFIX": "",
        "LINK_STATE_ROUTING": "ospf",
        "LINK_STATE_ROUTING_TAG": "VXLAN_UNDERLAY",
        "OSPF_AREA_ID": "0.0.0.0",
        "OSPF_AUTH_KEY_ID": "",
        "OSPF_AUTH_KEY": "",
        "ISIS_AUTH_KEYCHAIN_NAME": "",
        "IS_TYPE": "",
        "ISIS_P2P_ENABLE": "",
        "REPLICATION_MODE": "Multicast",
        "MTU": "9216",
        "BFD_ECHO_DISABLE": true,
        "DESC": "^UNDERLAY-Inter-Switch:vlan98",
        "CONF": " ip ospf bfd\n ip arp timeout 900",
        "ADMIN_STATE": true,
        "BFD_ENABLE": true,
        "BFD_AUTH_ENABLE": false,
        "BFD_AUTH_KEY_ID": "",
        "BFD_AUTH_KEY": "",
        "INTF_NAME": "Vlan98"
      }
```
**Additional context**
