### ISSUE TITLE
Support for VPC peer-link deployment

### ISSUE THREAD

**Issue by samurato** [CiscoDevNet/ansible-dcnm#174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected modules(s):  

* cisco.dcnm.dcnm_interface
### DCNM version

* V 11.5.1

### Potential ansible task config

```yaml
- name: Create port channel interfaces
  cisco.dcnm.dcnm_interface: &pc_merge
    fabric: "{{ targeted_fabric }}"
    state: merged                     
    config:
      - name: po1                     
        type: vpc                          
        switch:
          - "{{ ip }}"               
        deploy: false           
        profile:
          mode: vpc_peer_link ◄◄◄◄
          admin_state: true               
          peer1_members:                        
            - e1/53
            - e1/54
          pc_mode: 'on'               
          cmds:                           
            - service-policy type qos input QoS Mark-Ingress-Port-PM no-stats
          description: "port channel peering"
```

### References

**Additional context**
