### ISSUE TITLE
`dncm_policy` does not delete policies based on Policy ID

### ISSUE THREAD

**Issue by jgomezve** [CiscoDevNet/ansible-dcnm#201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

* ansible [core 2.12.3]

### DCNM version

* 12.1.2e

### Affected module(s)

* dcnm_policy

### Ansible Playbook

```yaml
---
- name: Create a Policies in the Nexus Dashboard Fabric Controller
  hosts: ndfc
  gather_facts: no
  tasks:

  - name: Delete policies using policy-id
    cisco.dcnm.dcnm_policy:
      fabric: "SIMPL-BROWNFIELD"
      state: deleted          # only choose form [merged, deleted, query]
      config:
        - name: POLICY-261210  # name is mandatory
          switch:
            - ip: 1.2.3.4

```

### Debug Output

PLAY [Create a Policies in the Nexus Dashboard Fabric Controller] ******************************************************************************

TASK [Delete policies using policy-id] *****************************************************************************************************
ok: [NDFC-FRA]

PLAY RECAP *********************************************************************************************************************************
NDFC-FRA   
### Expected Behavior

Policy is deleted

### Actual Behavior

Policy is not deleted

### Steps to Reproduce

Execute the playbook. The example is taken from the collection documentation

**Comment by mmudigon** [comment]
@jgomezve,

Thanks for raising the issue. Can you please give me the complete playbook that you used to create and delete the policy? We will check this and get back to you. If possible please collect ans share the output after executing the command with "-vvvvv" options.

**Comment by dsx1123** [comment]
@mmudigon  above playbook is enough to recreate this issue, here is the playbook:
```yaml
---
- name: Delete a Policy in the Nexus Dashboard Fabric Controller
  hosts: ndfc2
  gather_facts: no
  tasks:
  - name: Delete policies using policy-id
    cisco.dcnm.dcnm_policy:
      fabric: "fabric_n9kv"
      state: deleted          # only choose form [merged, deleted, query]
      config:
        - name: "POLICY-592740"
          switch:
            - ip: 192.168.123.13
```

and vvvv output:
https://gist.github.com/dsx1123/f527ef06f743a478cef9e8953472bfe1

**Comment by mmudigon** [comment]
@jgomezve, @dsx1123 

The format of the playbook is not correct. The "switch" element is a separate item under "config" and should not be under policies. The correct format is as below:

---
- name: Delete a Policy in the Nexus Dashboard Fabric Controller
  hosts: ndfc2
  gather_facts: no
  tasks:
  - name: Delete policies using policy-id
    cisco.dcnm.dcnm_policy:
      fabric: "fabric_n9kv"
      state: deleted
      config:
        - name: "POLICY-592740"
        **- switch:**
            - ip: 192.168.123.13

I have marked the change in bold above. Please try this and let me know if you still see any issue.

**Comment by mmudigon** [comment]
@jgomezve, @dsx1123

The format of the playbook is not correct. The "switch" element is a separate item under "config" and should not be under policies. The correct format is as below:

---
- name: Delete a Policy in the Nexus Dashboard Fabric Controller
  hosts: ndfc2
  gather_facts: no
  tasks:
  - name: Delete policies using policy-id
    cisco.dcnm.dcnm_policy:
      fabric: "fabric_n9kv"
      state: deleted
      config:
        - name: "POLICY-592740"
        - switch:
            - ip: 192.168.123.13

Please try this and let  me know. Note the "-" before switch.

**Comment by mmudigon** [comment]
The format of the playbook is not correct. The "switch" element is a separate item under "config" and should not be under policies. The correct format is as below:

```yaml
---
- name: Delete a Policy in the Nexus Dashboard Fabric Controller
  hosts: ndfc2
  gather_facts: no
  tasks:
  - name: Delete policies using policy-id
    cisco.dcnm.dcnm_policy:
      fabric: "fabric_n9kv"
      state: deleted
      config:
        - name: "POLICY-592740"
        - switch:
            - ip: 192.168.123.13
```

Please try this and let me know

**Comment by mmudigon** [comment]
Hi Shangxin,

The format of the playbook is not as expected. The ”switch” block must be a separate one under config since it is common to all policies. The correct format is as below:


---

- name: Delete a Policy in the Nexus Dashboard Fabric Controller

  hosts: ndfc2

  gather_facts: no

  tasks:

  - name: Delete policies using policy-id

    cisco.dcnm.dcnm_policy:

      fabric: "fabric_n9kv"

      state: deleted          # only choose form [merged, deleted, query]

      config:

        - name: "POLICY-592740"

        - switch:

            - ip: 192.168.123.13

Have responded to the issue in GIT with the same suggestion.

Thanks

Regards
Mallik

From: Shangxin Du ***@***.***>
Date: Tuesday, 28 February 2023 at 00:14
To: CiscoDevNet/ansible-dcnm ***@***.***>
Cc: MALLIK MUDIGONDA (mmudigon) ***@***.***>, Mention ***@***.***>
Subject: Re: [CiscoDevNet/ansible-dcnm] `dncm_policy` does not delete policies based on Policy ID (Issue #201)

@mmudigon<https://github.com/mmudigon> above playbook is enough to recreate this issue, here is the playbook:

---

- name: Delete a Policy in the Nexus Dashboard Fabric Controller

  hosts: ndfc2

  gather_facts: no

  tasks:

  - name: Delete policies using policy-id

    cisco.dcnm.dcnm_policy:

      fabric: "fabric_n9kv"

      state: deleted          # only choose form [merged, deleted, query]

      config:

        - name: "POLICY-592740"

          switch:

            - ip: 192.168.123.13

and vvvv output:
https://gist.github.com/dsx1123/f527ef06f743a478cef9e8953472bfe1

**Comment by jgomezve** [comment]
@mmudigon Thanks for you input.

I have tried the playbook below and it does not work. The playbook hangs forever

```yaml
---
- name: Create a Policies in the Nexus Dashboard Fabric Controller
  hosts: ndfc
  gather_facts: no
  tasks:

  - name: Delete policies using policy-id
    cisco.dcnm.dcnm_policy:
      fabric: "SIMPL-BROWNFIELD"
      state: deleted          # only choose form [merged, deleted, query]
      config:
        - name: POLICY-262440  # name is mandatory
        - switch: 
          - ip: 10.122.18.118
```

Why is the key `switch` another item inside the list `config`? In my personal opinion this is misleading for users. The way I see it the list `config`, is the list of policies to be deleted, each of them with its attributes (`name`, `ip`)

Moreover, Why is the switch ip required to delete a policy based on policyId ? According to the REST API Documentation, A policy can be deleted based solely on the Policy ID because a policy maps to a single switch
