### ISSUE TITLE
Module dcnm_vrf clears unsupported VRF Template properties

### ISSUE THREAD

**Issue by jgomezve** [CiscoDevNet/ansible-dcnm#207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

* 2.12.3

### DCNM version

* V 12.1.2e

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
  - name: Merge vrfs
    cisco.dcnm.dcnm_vrf:
      fabric: myFabric
      state: merged
      config:
      - vrf_name: VRF-TEST
        vrf_id: 10010
        vrf_template: myVrfTemplate
        vrf_extension_template: myVrfExtensionTemplate
        vlan_id: 2010
        service_vrf_template: null
        attach:
        - ip_address: 1.2.3.4
          deploy: true

```

### Debug Output

The module `dcnm_rest` is being used to create/update a VRF, and then the modules `dcnm_vrf` to deploy/ attaches to the switches

The playbook is executed without any problem however most of the VRF attributes, the ones not supported by the module, are cleared

### Expected Behavior

Properties not supported by the module should be left untouched

### Actual Behavior

Properties such as MTU, Tag, Max BGP paths etc are cleard from the VRF config

### Steps to Reproduce

* Create a VRF manually in NDFC or using the `dcnm_rest` module
* Execute the playbook
* Attributes not supported by the modules are cleared

### References

The root cause seem to be a "limitation" in the NDFC Rest API. I have manually create a VRF and then updated it via Postman with the following payload

```json
{
    "displayName": "VRF-TEST",
    "fabric": "myFabric",
    "vrfExtensionTemplate": "myVrfExtensionTemplate",
    "vrfId": 10011,
    "vrfName": "VRF-TEST"",
    "vrfTemplate": "myVrfTemplate",
    "vrfTemplateConfig": "{\"vrfName\":\"VRF-TEST\",\"vrfVlanId\":2010,\"vrfSegmentId\":10011,\"nveId\":\"1\",\"asn\":\"\"}"
}
```

The keys in the `vrfTemplateConfig` are the ones that seem to be used by the module. See:

https://github.com/CiscoDevNet/ansible-dcnm/blob/851149a9334fb78a3d2d1ca2a8e7a8500ccddc6e/plugins/modules/dcnm_vrf.py#L1651
