### ISSUE TITLE
dcnm_vrf vrf_lite auto dot1q allocation doesn't work as expected

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

```
ansible [core 2.12.10]
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/virtualenv/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/virtualenv/ansible/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### DCNM version

* V 12.1.2e

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here 
---
- name: VRF Lite issue
  hosts: ndfc2
  gather_facts: false
  tasks:
    - name: config vrf_lite
      cisco.dcnm.dcnm_vrf:
        fabric: fabric_n9kv
        config:
          - vrf_name: "{{item}}"
            attach:
              - ip_address: 192.168.123.13
                vrf_lite:
                - peer_vrf: "{{item}}"
                  interface: Ethernet1/1
                  ipv4_addr: 10.33.0.1/30
                  neighbor_ipv4: 10.33.0.2
      loop:
        - vrf_red
        - vrf_blue

```

### Debug Output

https://gist.github.com/dsx1123/afacb77fcd7ad257cd95239804549c7a
### Expected Behavior

second vrf vrf_blue should use 3 as dot1q tag
### Actual Behavior

playbook failed as second vrf is still using tag 2, NDFC reject the API
