### ISSUE TITLE
module error when deploy second vrf using state=overridden 

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version
```
ansible [core 2.12.2]
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/virtualenv/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/virtualenv/ansible/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

### DCNM version

* V 12.1.2e

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
# Copy-paste your ansible playbook here
---
- name: vrf overridden
  hosts: ndfc2
  vars:
    fabric: fabric_stage
    vrf_config:
      - vrf_name: vrf_green
        vrf_id: 51011
        attach:
          - ip_address: 192.168.123.101
            deploy: false
          - ip_address: 192.168.123.102
            deploy: false
     # vrf_blue is added after the first run
      - vrf_name: vrf_blue
        vrf_id: 51012
        attach:
          - ip_address: 192.168.123.101
            deploy: false
          - ip_address: 192.168.123.102
            deploy: false
  tasks:

    - name: overridden vrfs
      cisco.dcnm.dcnm_vrf:
        fabric: "{{ fabric}}"
        state: overridden
        config: "{{ vrf_config }}"
      tags:
        - vrf
        - overlay

```

### Debug Output

https://gist.github.com/dsx1123/e929659048986aa6ff58478bd7d3657c

### Expected Behavior
The second vrfs should be created 

### Actual Behavior
module error

### Steps to Reproduce
1. create first vrf vrf_green using playbook
2. attach the vrf to switch and deploy
3. add second vrf vrf_blue to the playbook and re-run the playbook

### References
the issue might be related to #230,
And if set deploy=true, the issue is not seen.
