### ISSUE TITLE
dcnm_link error when trying to modify the auto-discovered link

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

```
ansible [core 2.12.6]
  config file = /home/shdu/.ansible.cfg
  configured module search path = ['/home/shdu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shdu/virtualenv/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/shdu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/shdu/virtualenv/ansible/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True

```

### DCNM version

* V 12.1.2e

### Affected module(s)

* dcnm_link

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here 
   - name: modify links between leaf and spine
      cisco.dcnm.dcnm_links:
        src_fabric: "{{ fabric.name }}"
        config:
          - dst_fabric: "{{ fabric.name }}"
            src_device: "{{ fabric.leaf[0] }}"
            dst_device: "{{ fabric.spine[0] }}"
            src_interface: "Ethernet1/5"
            dst_interface: "Ethernet1/1"
            template: int_intra_fabric_num_link
            profile:
              peer1_ipv4_addr: 10.30.1.1
              peer2_ipv4_addr: 10.30.1.2
              peer1_ipv6_addr: ""
              peer2_ipv6_addr: ""
              admin_state: true
              mtu: 9216

```

### Debug Output

https://gist.github.com/dsx1123/764737ed309378de23f41bb0e6ae62c8
### Steps to Reproduce

this link is auto-discovered during adding switches. so the template name is empty which cause the bug.
