### ISSUE TITLE
support secondary_ip of loopback interface

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected modules(s):

* dcnm_interface

### NDFC version

* V 12.1.2e

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
- name: Create loopback interfaces
  cisco.dcnm.dcnm_interface: 
    fabric: mmudigon-fabric
    state: merged                         # only choose from [merged, replaced, deleted, overridden, query]
    config:
      - name: lo100                       # should be of the form lo<port-id>
        type: lo                          # choose from this list [pc, vpc, sub_int, lo, eth]
        switch:
          - "192.172.1.1"                 # provide the switch where to deploy the config
        deploy: true                      # choose from [true, false]
        profile:
          admin_state: true               # choose from [true, false]
          mode: lo                        # choose from [lo]
          int_vrf: ""                     # VRF name
          ipv4_addr: 192.169.10.1         # ipv4 address for the loopback interface
          secondary_ip: 192.168.10.2.     # secondary ipv4 address for loopback interface
          ipv6_addr: fd01::0201           # ipV6 address for the loopback interface
          route_tag: ""                   # Routing Tag for the interface
          cmds:                           # Freeform config
            - no shutdown
          description: "loopback interface 100 configurations"

```

### References

![image](https://github.com/CiscoDevNet/ansible-dcnm/assets/3794076/8a840a4f-a1cb-4be1-a8de-ff336fc07cba)

**Additional context**
