### ISSUE TITLE
support MPLS extension when attach the vrf to the border

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected modules(s):

* dcnm_vrf

### DCNM version

* V 12.1.2e

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
- name: MPLS handoff
  fabric: vxlan_evpn
  config:
  - vrf_name: vrf_blue
    vrf_id: 50002
    attach:
      - ip_address: 172.31.217.101
      - ip_address: 172.31.217.103
      - ip_address: 172.31.186.156
        import_evpn_rt: 50000:1000
        export_evpn_rt: 50000:1000
```

### References

**Additional context**
https://www.cisco.com/c/en/us/td/docs/dcn/ndfc/1212/configuration/fabric-controller/cisco-ndfc-fabric-controller-configuration-guide-1212/m-configuring-mpls.html
