### ISSUE TITLE
Support attach network to TOR switches and interfaces

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected modules(s):

* dcnm_network

### DCNM version

* V 12.1.2e

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
  - name: create network
      cisco.dcnm.dcnm_network:
        fabric: "{{ fabric.name }}"
        config:
          - net_name: network1
            vlan_id: 2300
            vrf_name: vrf1
            attach:
              - ip_address: "192.168.123.101"
                ports:
                  - Ethernet1/13
                  - Ethernet1/14
                tor_ports:
                  - ip_address: 192.168.123.105
                    ports:
                      - Ethernet1/13
                      - Ethernet1/14
              - ip_address: "192.168.123.102"
                ports:
                  - Ethernet1/13
                  - Ethernet1/14
                tor_ports:
                  - ip_address: 192.168.123.105
                    ports:
                      - Ethernet1/13
                      - Ethernet1/14

```
The fabric.tor.0 and fabric.tor.1 are the TOR switches's IP, module should detect the role of the switch, based on the tor, this is the payload of attach API(only supported on NDFC)

```json
[
   {
      "networkName":"network1",
      "lanAttachList":[
         {
            "fabric":"fabric_manual",
            "networkName":"network1",
            "serialNumber":"93Q20AEGJUD",
            "switchPorts":"Ethernet1/1",
            "detachSwitchPorts":"",
            "torPorts":"tor1(eth1/1)",
            "vlan":2301,
            "dot1QVlan":1,
            "untagged":false,
            "freeformConfig":"",
            "deployment":true,
            "extensionValues":"",
            "instanceValues":"{\"isActive\":false}"
         },
         {
            "fabric":"fabric_manual",
            "networkName":"network1",
            "serialNumber":"9OK4E76315Z",
            "switchPorts":"Ethernet1/1",
            "detachSwitchPorts":"",
            "torPorts":"tor1(eth1/1)",
            "vlan":2301,
            "dot1QVlan":1,
            "untagged":false,
            "freeformConfig":"",
            "deployment":true,
            "extensionValues":"",
            "instanceValues":"{\"isVPC\":true,\"isActive\":false}"
         }
      ]
   }
]
```
### References

https://www.cisco.com/c/en/us/td/docs/dcn/ndfc/1212/configuration/fabric-controller/cisco-ndfc-fabric-controller-configuration-guide-1212/m-configuring-tor-switches_2.html
**Additional context**
