### ISSUE TITLE
dcnm_image_upload module

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected modules(s):

* dcnm_image_upload

### DCNM version

* V 12.1.3

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
    - name: Upload Images
      cisco.dcnm.dcnm_image_upload:
      state: merged                             # choose from merged, deleted, overriden, and query
      files:
        - path: /nxos/nxos64-cs.10.3.2.F.bin    # mandatory, this path can be local file path or paht of remote server
          source: scp                           # choose from local, scp, and sftp, default is local we might support other protocols in the future
          remote_server: file-server.cisco.com  # optional, only used when the source is scp
          username: shdu                        # optional, only used when the source is scp
          password: password                    # optional, only used when the source is scp
        - path: /local_folder/n3100-compact.7.0.3.I7.10.bin
          source: local

```
This module should only support 12.1.3 onwards.
### References

https://www.cisco.com/c/en/us/td/docs/dcn/ndfc/1212/configuration/fabric-controller/cisco-ndfc-fabric-controller-configuration-guide-1212/image-management.html
**Additional context**
