### ISSUE TITLE
dcnm_image_policy

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
New module to create image policy

### New or Affected modules(s):

* dcnm_image_policy

### DCNM version

* V 12.1.3

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
    - name: Create Image polices
      cisco.dcnm.dcnm_image_policy:
        state: merged                                                   # choose from merged, replaced, overridden, deleted, query
        config:
          - name: NR3F                                                  # mandatory, name of the policy
            description: image policy of 10.3(3)F                       # optional, description of the policy
            platform: N9K                                               # mandatory, no default, choose from N9K, N7K, N77, N6K, N5K
            release: 10.3.1_nxos64-cs_64bit                             # mandatory, no default, please see the API doc for example
            packages:                                                   # optional, list of rpm packages
              - mtx-openconfig-all-2.0.0.0-10.4.1.src.rpm
            epld_image: n9000-epld.10.3.2.F.img                         # optional, default is ""
            disabled_rpm: mtx-grpctunnel-2.1.0.0-10.4.1.lib32_64_n9000  # optional, default is ""
            agnostic: false                                             # optional, default is false, this indicates whether the packages provided are the same version as the release

```

### References

https://www.cisco.com/c/en/us/td/docs/dcn/ndfc/1212/configuration/fabric-controller/cisco-ndfc-fabric-controller-configuration-guide-1212/image-management.html
**Additional context**

**Comment by allenrobel** [comment]
Hi all.  My understanding is that ``packages`` relates to rpm packages that are to be installed, whereas ``rpmimages`` (from REST API)  (referred to as ``disabled_rpm`` in the "Potential ansible task config" is a list of rpm packages to uninstall.

I'm implemented this as shown below.  Please let me know if any concerns.

```yaml
    tasks:
    -   name: Merge Image policies
        cisco.dcnm.dcnm_image_policy:
            state: merged
            config:
            -   name: KR5M
                agnostic: false
                description: KR5M
                epld_image: n9000-epld.10.2.5.M.img
                packages:
                   install:
                   - mtx-openconfig-all-2.0.0.0-10.4.1.src.rpm
                   uninstall:
                   - mtx-grpctunnel-2.1.0.0-10.4.1.lib32_64_n9000
                platform: N9K
                release: 10.2.5_nxos64-cs_64bit
                type: PLATFORM
```
