### ISSUE TITLE
cisco.dcnm.dcnm_interface - Duplex Setting

### ISSUE THREAD

**Issue by xXAzazelXx** [CiscoDevNet/ansible-dcnm#284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be please possible to add "duplex"  to the cisco.dcnm.dcnm_interface module?
At the moment we are unable to specify the duplex setting in cisco.dcnm.dcnm_interface playbooks

### New or Affected modules(s):

* dcnm_3.4.3

### DCNM version

* V 12.1.2e

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
```

    - name: Create Access Port using variables
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric_name }}"
        state: merged
        config:
          - name: '{{ item.Interface }}'
            type: eth
            switch: 
            - '{{ item.Hostname }}'
            deploy: false
            profile:
              admin_state: true
              mode: access
              access_vlan: '{{ item.VLAN }}'
              bpdu_guard: '{{ item.BPDU_Guard }}'
              description: '{{ item.Description }}'
              mtu: jumbo
              port_type_fast: true
              speed: '{{ item.Speed }}'
              duplex: full <-------
              
### References

**Additional context**

**Comment by mikewiebe** [comment]
Does not look like NDFC exposes `duplex` as a property but you can set it using the `cmds` option from the module.

Something like this:

```yaml
- name: Create Access Port using variables
  cisco.dcnm.dcnm_interface:
    fabric: "{{ fabric_name }}"
    state: merged
    config:
      - name: '{{ item.Interface }}'
        type: eth
        switch: 
        - '{{ item.Hostname }}'
        deploy: false
        profile:
          admin_state: true
          mode: access
          access_vlan: '{{ item.VLAN }}'
          bpdu_guard: '{{ item.BPDU_Guard }}'
          description: '{{ item.Description }}'
          mtu: jumbo
          port_type_fast: true
          speed: '{{ item.Speed }}'
          cmds:
              - duplex full
```
