### ISSUE TITLE
`dcnm_fabric` with replaced state should create the fabric if doesn't exist

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version
```
ansible [core 2.16.7]
  config file = /home/shdu/.ansible.cfg
  configured module search path = ['/home/shdu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shdu/virtualenv/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/shdu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/shdu/virtualenv/ansible/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/shdu/virtualenv/ansible/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### DCNM version

* V 12.1.3e

### Affected module(s)

* dcnm_fabric

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here
---
- name: Build fabric1
  hosts: ndfc_eft
  gather_facts: false
  vars:
    fabric: "{{ fabric1 }}"
  tasks:
    - name: Create fabric {{ fabric.name }}
      vars:
        fabric_config:
          FABRIC_NAME: "{{ fabric.name }}"
          FABRIC_TYPE: VXLAN_EVPN
          BGP_AS: "{{ fabric.asn }}"
          OVERLAY_MODE: "cli"
          GRFIELD_DEBUG_FLAG: "Enable"
          AAA_REMOTE_IP_ENABLED: false
          UNDERLAY_IS_V6: false
          ENABLE_SGT: false
          ENABLE_PVLAN: false
          STATIC_UNDERLAY_IP_ALLOC: false
          ANYCAST_RP_IP_RANGE: "{{ fabric.anycast_rp_ip_range }}"
          DCI_SUBNET_RANGE: "{{ fabric.dci_subnet_range }}"
          LOOPBACK0_IP_RANGE: "{{ fabric.loopback0_ip_range }}"
          LOOPBACK1_IP_RANGE: "{{ fabric.loopback1_ip_range }}"
          SUBNET_RANGE: "{{ fabric.subnet_range }}"
          DEPLOY: true
      cisco.dcnm.dcnm_fabric:
        state: replaced
        config:
          - "{{ fabric_config }}"
      register: result
      tags:
        - inveontry

```

### Debug Output

https://gist.github.com/dsx1123/f4aa4fe44eb309bd53ee1062552c110b

### Expected Behavior

The fabric doesn't exist on the NDFC, it should be created when run it first.

### Actual Behavior

task returns ok without creating the fabric.
