### ISSUE TITLE
dcnm_network: KeyError when querying network that doesn't exist.

### ISSUE THREAD

**Issue by allenrobel** [CiscoDevNet/ansible-dcnm#314]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

```
ansible [core 2.16.6]
  config file = /Users/arobel/repos/ndfc-roles-prod/ansible.cfg
  configured module search path = ['/Users/arobel/repos/ansible_dev/dcnm_fabric/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arobel/repos/ansible_dev/dcnm_fabric/ansible_collections/cisco/dcnm/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/arobel/repos/ansible_dev/dcnm_fabric
  executable location = /Users/arobel/repos/ansible_dev/dcnm_fabric/ansible_collections/cisco/dcnm/.venv/bin/ansible
  python version = 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] (/Users/arobel/repos/ansible_dev/dcnm_fabric/ansible_collections/cisco/dcnm/.venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### DCNM version

* V 3.2.1e

### Affected module(s)

* dcnm_network

### Ansible Playbook

Below, ``new-network`` does not exist.

```yaml
- hosts: ndfc
  gather_facts: false
  tasks:
    - name: Demo Query network
      cisco.dcnm.dcnm_network:
        fabric: Fab1
        state: query
        config:
        - net_name: new-network
      register: network_config
```

### Debug Output

[Debug Output](https://gist.github.com/allenrobel/c49cdc55d50c22e82b0843a3054ddf7d)

### Expected Behavior

Module should not crash and should return output indicating that the network does not exist.

### Actual Behavior

A KeyError exception occurs.

### Steps to Reproduce

Run the above playbook when ``new-network`` does not exist in fabric ``Fab1``
