### ISSUE TITLE
VRF extension subinterface MTU conflicts with parent interface MTU.

### ISSUE THREAD

**Issue by gnakh** [CiscoDevNet/ansible-dcnm#318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible [core 2.17.2]
python version = 3.12.4 (main, Jun  6 2024, 18:26:44)
jinja version = 3.1.4
libyaml = True

### NDFC version

* V 12.2.2.238

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
    - name: Create and attach VRFs to switches in {{ defaults.MSD_fabric_name }} fabric
      cisco.dcnm.dcnm_vrf:
        fabric: '{{ defaults.msd.fabric_name }}'
        state: '{{ state | default("merged") }}'
        config: '{{ vrfs_for_module }}'
      tags: vrfs
```
Values:

```yaml
vrfs_for_module:
  - vrf_name: infra
    vrf_id: 51000
    vrf_template: '{{ defaults.vrf_template }}'
    vrf_extension_template: '{{ defaults.extension_vrf_template }}'
    vlan_id: 3100
    vrf_int_mtu: 9000
    attach:
    - ip_address: 198.18.154.16 
      vrf_lite:
        - peer_vrf: corp
          ipv4_addr: 172.16.12.2/30
          neighbor_ipv4: 172.16.12.1
          interface: Ethernet1/24
          dot1q: 100
        - peer_vrf: corp
          ipv4_addr: 172.16.12.10/30
          neighbor_ipv4: 172.16.12.9
          interface: Ethernet1/25
          dot1q: 100
      deploy: true
      deploy: true

### Debug Output

### Expected Behavior

Subinterface used for VRF lite is configured with the value configured for that link in NDFC ext_fabric_setup MTU field 

### Actual Behavior

Subinterface used for VRF lite is configured with MTU 9216 regardless of what NDFC is configured with in the ext_fabric_setup MTU field 

### Steps to Reproduce

Configure the MTU of the parent interface to 9000
Configure the MTU in the ext_fabric_setup to 9000
Deploy a VRF extension on that interface. Deployment to the switch will fail with the following error:

CLI command ' mtu 9216' failed with following error:Delivery failed with message:MTU of sub-interface greater than parent interface detected

Playbook finishes successfuly.
