### ISSUE TITLE
VRF module does not catch 'Failed' messages in the DATA field of the response from NDFC.

### ISSUE THREAD

**Issue by gnakh** [CiscoDevNet/ansible-dcnm#324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible [core 2.17.2]
dcnm collection ver 3.4.3

### DCNM version

* 12.2.2.238

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
    - name: Create and attach VRFs to switches in {{ defaults.msd.fabric_name }} fabric
      cisco.dcnm.dcnm_vrf:
        fabric: '{{ defaults.msd.fabric_name }}'
        state: '{{ state | default("merged") }}'
        config: '{{ extra_vrfs }}'
      tags: vrfs
```

This is a sample VRF. Border leaves are 154.16 and 154.17
```yaml
extra_vrfs:
extra_vrfs:
  - vrf_name: iot
    vrf_id: 51200
    max_bgp_paths: 4
    vrf_template: '{{ defaults.vrf_template }}'
    vrf_extension_template: '{{ defaults.extension_vrf_template }}'
    vlan_id: 3200
    vrf_int_mtu: 9000
    #source: 123
    #service_vrf_template: null
    attach:
    - ip_address: 198.18.167.9
      deploy: true
    - ip_address: 198.18.167.8
      deploy: true
    - ip_address: 198.18.165.133 
      deploy: true           
    - ip_address: 198.18.167.25 
      deploy: true
    - ip_address: 198.18.167.19 
      deploy: true
    - ip_address: 198.18.154.16 
      vrf_lite:
        - peer_vrf: iot
          ipv4_addr: 172.16.12.2/30
          neighbor_ipv4: 172.16.12.1
          interface: Ethernet1/24
          dot1q: 200
          #extension_subint_mtu: 9000
        - peer_vrf: iot
          ipv4_addr: 172.16.12.10/30
          neighbor_ipv4: 172.16.12.9
          interface: Ethernet1/25
          dot1q: 200
          #extension_subint_mtu: 9000      
        - peer_vrf: iot
          ipv4_addr: 172.16.12.18/30
          neighbor_ipv4: 172.16.12.17
          interface: Ethernet1/26
          dot1q: 200
          #extension_subint_mtu: 9000
        - peer_vrf: iot
          ipv4_addr: 172.16.12.26/30
          neighbor_ipv4: 172.16.12.25
          interface: Ethernet1/27
          dot1q: 200
          #extension_subint_mtu: 9000          
      deploy: true
    - ip_address: 198.18.154.17 
      vrf_lite:
        - peer_vrf: iot
          ipv4_addr: 172.16.12.6/30
          neighbor_ipv4: 172.16.12.5
          interface: Ethernet1/24
          dot1q: 200
          #extension_subint_mtu: 9000
        - peer_vrf: iot
          ipv4_addr: 172.16.12.14/30
          neighbor_ipv4: 172.16.12.13
          interface: Ethernet1/25
          dot1q: 200
          #extension_subint_mtu: 9000      
        - peer_vrf: iot
          ipv4_addr: 172.16.12.22/30
          neighbor_ipv4: 172.16.12.21
          interface: Ethernet1/26
          dot1q: 200
          #extension_subint_mtu: 9000
        - peer_vrf: iot
          ipv4_addr: 172.16.12.30/30
          neighbor_ipv4: 172.16.12.29
          interface: Ethernet1/27
          dot1q: 200
          #extension_subint_mtu: 9000
      deploy: true
```

The playbook as such is more or less irrelevant. Anything that creates a VRF would work.

### Debug Output

  "response": [
        {
            "DATA": {},
            "MESSAGE": "OK",
            "METHOD": "PUT",
            "REQUEST_PATH": "https://198.18.131.10:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/XXX_MSD/vrfs/iot",
            "RETURN_CODE": 200
        },
        {
            "DATA": {},
            "MESSAGE": "OK",
            "METHOD": "PUT",
            "REQUEST_PATH": "https://198.18.131.10:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/XXX_MSD/vrfs/guest",
            "RETURN_CODE": 200
        },
        {
            "DATA": {
                "guest-[FDO22282VHK/BSLEAF101]-[FDO22283XXX/BSLEAF102]": "Attach Response : Failed : VPC details not found for Peer Serial no: FDO22283XXX",
                "iot-[FDO22282VHK/BSLEAF101]-[FDO22283XXX/BSLEAF102]": "Attach Response : Failed : VPC details not found for Peer Serial no: FDO22283XXX"
            },
            "MESSAGE": "OK",
            "METHOD": "POST",
            "REQUEST_PATH": "https://198.18.131.10:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/XXX_MSD/vrfs/attachments",
            "RETURN_CODE": 200
        },
        {
            "DATA": {
                "status": "Deployment of VRF(s) has been initiated successfully"
            },
            "MESSAGE": "OK",
            "METHOD": "POST",
            "REQUEST_PATH": "https://198.18.131.10:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/XXX_MSD/vrfs/deployments",
            "RETURN_CODE": 200
        }
    ]
}  

The task is still successful:
PLAY RECAP *****************************************************************************************************************************************************************************************************
cpoc-xxxxxx                : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 

CSCwh23123 describes what that "Failed" message actually means. The configuration between the two peers is inconsistent. Will explain later.

### Expected Behavior

Changes to the VRF are added to the NDFC DB and finally pushed to the switches

### Actual Behavior

VRF is configured in the NDFC DB but not attached to the border leaf that renders the error. Because it is not attached, configuration is consistent between the switch and NDFC DB and it will never be pushed to the leaf. 

### Steps to Reproduce
Ran into this issue while trying to create a new attachment for the VRF. 
 
Create a VRF and delete it. Run the task while the VRF is in Delete Holddown state in the border leaf.

BSLEAF101# show vrf
VRF-Name                           VRF-ID State   Reason
default                                 1 Up      --
egress-loadbalance-resolution-          3 Up      --
guest                                  17 Down    Delete Holddown
infra                                  12 Up      --
iot                                    18 Down    Delete Holddown
management                              2 Up      --
