### ISSUE TITLE
Policy module fails when using policy as key flag if a policy already exists in NDFC but doesn't have a description field

### ISSUE THREAD

**Issue by mthurstocisco** [CiscoDevNet/ansible-dcnm#338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible [core 2.16.3]

### DCNM version

* V 12.2.2.238

### Affected module(s)

* dcnm_policy

### Ansible Playbook

```yaml
- name: Manage NDFC Fabric Policies
  cisco.dcnm.dcnm_policy:
    fabric: fabric_name
    use_desc_as_key: true
    config: 
        - create_additional_policy: False
          description: feature_ospf
          name: feature_ospf
          policy_vars:
          priority: 60
       - switch:
             - ip: 1.2.3.4
    deploy: false
    state: merged
```

### Debug Output
To hit this problem it would require NDFC to already an instance of the same policy on the same switch but with the description field being blank.

When running you get a key error when the description is currently blank in NDFC (in my example i was trying to create feature_ospf but it was already in NDFC from the fabric creation).

In terms of expected behavior, maybe a error raised up to the user telling them a policy with that template already exists in NDFC but without a description? I guess on brownfield deployments (where potentially you want to start using ansible but have previously configured things via the GUI) this would come up a lot.
