### ISSUE TITLE
dcnm_fabric: External fabric types should add EXT_FABRIC_TYPE to the POST request payload.

### ISSUE THREAD

**Issue by allenrobel** [CiscoDevNet/ansible-dcnm#343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acknowledgement

Thank you to Alessandro De Prato for bringing this issue to our attention.

### Ansible Version and collection version

```
ansible [core 2.16.4]
  config file = /Users/arobel/.ansible.cfg
  configured module search path = ['/Users/arobel/repos/ansible_dev/dcnm_fabric/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arobel/py312/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/arobel/repos/ansible_dev/dcnm_fabric
  executable location = /Users/arobel/py312/bin/ansible
  python version = 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] (/Users/arobel/py312/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True
```

### DCNM version

* V 3.6.0

### Affected module(s)

* dcnm_fabric

### Ansible Playbook

```yaml
- name: dcnm_fabric_test
  hosts: ndfc
  tasks:
    -   name: merge ISN fabric
        cisco.dcnm.dcnm_fabric:
            state: merged
            config:
             -   FABRIC_NAME: ISN
                 BGP_AS: 65022
                 FABRIC_TYPE: ISN
```

### Expected Behavior

After merging the above fabric, the `Fabric Type` column in the  NDFC GUI (`NDFC -> Manage -> Fabrics`) should display "Multi-Site External Network".

### Actual Behavior

After merging the above fabric, the `Fabric Type` column in the  NDFC GUI (`NDFC -> Manage -> Fabrics`) displays "Custom Fabric".

### Steps to Reproduce

Run the provided playbook.

### Workaround

Until a fix is integrated, the following modification to the playbook will nudge NDFC to display a proper label for ISN fabric type.  The `EXT_FABRIC_TYPE` key is used only for fabrics that use the `External_Fabric` template.

```yaml
- name: dcnm_fabric_test
  hosts: ndfc
  tasks:
    -   name: merge ISN fabric
        cisco.dcnm.dcnm_fabric:
            state: merged
            config:
             -   FABRIC_NAME: ISN
                 BGP_AS: 65022
                 EXT_FABRIC_TYPE: "Multi-Site External Network"
                 FABRIC_TYPE: ISN
```
