### ISSUE TITLE
dcnm_vrf: infinite loop in wait_for_vrf_del_ready()

### ISSUE THREAD

**Issue by allenrobel** [CiscoDevNet/ansible-dcnm#351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

```
ansible [core 2.17.5]
  config file = /Users/arobel/.ansible.cfg
  configured module search path = ['/Users/arobel/repos/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arobel/repos/ndfc-python/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/arobel/repos/ansible/collections
  executable location = /Users/arobel/repos/ndfc-python/.venv/bin/ansible
  python version = 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (/Users/arobel/repos/ndfc-python/.venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### DCNM version

* V 3.6.0

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
- name: Minimal reproduce for VRF deleted infinite loop
  hosts: ndfc
  vars:
    FABRIC_NAME: FABRIC_1
    FABRIC_BGP_AS: 65001
    NETWORK_NAME: NETWORK_1
    VRF_NAME: VRF_1
    LEAF_IP4: 10.1.1.2
    ATTACH_PORTS: ["Ethernet1/9"]
    SWITCH_USERNAME: admin
    SWITCH_PASSWORD: MySwitchPassword

  tasks:
    - name: Create fabric
      cisco.dcnm.dcnm_fabric:
        state: merged
        config:
        - FABRIC_NAME: "{{ FABRIC_NAME }}"
          FABRIC_TYPE: VXLAN_EVPN
          BGP_AS: "{{ FABRIC_BGP_AS }}"

    - name: Add leaf
      cisco.dcnm.dcnm_inventory:
        fabric: "{{ FABRIC_NAME }}"
        state: merged
        config:
        - seed_ip: "{{ LEAF_IP4 }}"
          auth_proto: MD5
          user_name: "{{ SWITCH_USERNAME }}"
          password: "{{ SWITCH_PASSWORD }}"
          max_hops: 0
          role: leaf
          preserve_config: False
      register: result

    - name: Wait for switch to fully reload
      pause:
        seconds: 180
      when: result.changed

    - name: deploy
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ FABRIC_NAME }}/config-deploy?forceShowRun=false"
      when: result.changed

    - name: Merge VRF
      cisco.dcnm.dcnm_vrf:
        fabric: "{{ FABRIC_NAME }}"
        state: merged
        config:
        - vrf_name: "{{ VRF_NAME }}"
          vrf_id: 50101 
          adv_default_routes: false
          static_default_route: false
          vrf_template: Default_VRF_Universal
          vrf_extension_template: Default_VRF_Extension_Universal
          vlan_id: 201
          vrf_int_mtu: 9000
          attach:
          - ip_address: "{{ LEAF_IP4 }}"
            deploy: true
      register: result

    - name: deploy
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ FABRIC_NAME }}/config-deploy?forceShowRun=false"
      when: result.changed

    - name: Merge Network
      cisco.dcnm.dcnm_network:
        fabric: '{{ FABRIC_NAME }}'
        state: merged
        config:
        - net_name: "{{ NETWORK_NAME }}"
          vrf_name: "{{ VRF_NAME }}"
          net_id: 30101
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          l3gw_on_border: true
          vlan_id: 101
          gw_ip_subnet: 172.16.14.1/24
          attach:
            - ip_address: "{{ LEAF_IP4 }}" 
              deploy: true
              ports: "{{ ATTACH_PORTS }}"
          deploy: true
          multicast_group_address: 239.1.1.1
      when: result.changed

    - name: deploy
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ FABRIC_NAME }}/config-deploy?forceShowRun=false"

    - name: Wait for network merge to deploy
      pause:
        seconds: 60
      when: result.changed

    - name: Delete VRF
      cisco.dcnm.dcnm_vrf:
        fabric: '{{ FABRIC_NAME }}'
        state: deleted
        config:
        - vrf_name: "{{ VRF_NAME }}"
```

### Debug Output

Since `lanAttachState` below is `DEPLOYED` the following while loop conditional is hit, which sets state to False, so the loop is never exited.

```python
            for vrf in self.diff_delete:
                state = False
                # ...
                while not state:
                    resp = dcnm_send(self.module, method, path)
                    state = True
                    if resp.get("DATA") is not None:
                        attach_list = resp["DATA"][0]["lanAttachList"]
                            # ...
                            if atch["lanAttachState"] != "NA":
                                self.diff_delete.update({vrf: "DEPLOYED"})
                                state = False
                                time.sleep(self.WAIT_TIME_FOR_DELETE_LOOP)
                                break
```

```
2024-12-02 14:46:59,570 - DEBUG - [dcnm.DcnmVrf.wait_for_vrf_del_ready.2784] DcnmVrf.wait_for_vrf_del_ready: attach_list: [
    {
        "vrfName": "VRF_1",
        "switchName": "cvd-2311-leaf",
        "lanAttachState": "DEPLOYED",
        "isLanAttached": true,
        "switchSerialNo": "FDO211218HB",
        "peerSerialNo": null,
        "switchRole": "leaf",
        "fabricName": "FABRIC_1",
        "ipAddress": "172.22.150.106",
        "instanceValues": "{\"loopbackIpV6Address\":\"\",\"loopbackId\":\"\",\"deviceSupportL3VniNoVlan\":\"false\",\"switchRouteTargetImportEvpn\":\"\",\"loopbackIpAddress\":\"\",\"switchRouteTargetExportEvpn\":\"\"}",
        "vlanId": 201,
        "vrfId": 50101,
        "entityName": "VRF_1"
    }
]
```

### Expected Behavior

We should exit with an error if `lanAttachedState` == `DEPLOYED` and `isLanAttached ` == True

### Actual Behavior

We loop forever.

### Steps to Reproduce

Modify and run the attached playbook.
