### ISSUE TITLE
dcnm_vrf: 500 error at /rest/top-down/fabrics/f1/vrfs/attachments

### ISSUE THREAD

**Issue by allenrobel** [CiscoDevNet/ansible-dcnm#357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

While running the merged-state integration test, dcnm_vrf appears to be sending an invalid payload, which results in the following 500 error response:

```
"com.google.gson.JsonArray incompatible with com.google.gson.JsonObject"
```

### DCNM version

* V 3.6.0

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

This happens when the following test from the `merged.yaml` integration test is run.

```yaml
- name: TEST.3 - MERGED - [merged] Create, Attach, Deploy VLAN+VRF+LITE EXTENSION ansible-vrf-int1 switch_2 (user provided)
  cisco.dcnm.dcnm_vrf: &conf3
    fabric: "{{ fabric_1 }}"
    state: merged
    config:
    - vrf_name: ansible-vrf-int1
      vrf_id: 9008011
      vrf_template: Default_VRF_Universal
      vrf_extension_template: Default_VRF_Extension_Universal
      vlan_id: 500
      attach:
      - ip_address: "{{ switch_1 }}"
      - ip_address: "{{ switch_2 }}"
        vrf_lite:
          - peer_vrf: ansible-vrf-int1 # optional
            interface: "{{ interface_2a }}" # mandatory
            ipv4_addr: 10.33.0.2/30 # optional
            neighbor_ipv4: 10.33.0.1 # optional
            ipv6_addr: 2010::10:34:0:7/64 # optional
            neighbor_ipv6: 2010::10:34:0:3 # optional
            dot1q: 2 # dot1q can be got from dcnm
      deploy: true
  register: result_3

```

### Debug Output

[500 vs 200 responses with their payloads](https://gist.github.com/allenrobel/bcfcace899e6e1180e307ad606015ede)

### Expected Behavior

We should get a 200 response.

### Actual Behavior

We get a 500 response

#### Topology

- edge router is in an ISN fabric
- bgw_1 is switch_1 in the merged.yaml file.
- bgw_2 is switch_2 in the merged.yaml file.
- bgw_2.Eth2/9 is interface_2a in the merged.yaml file.

```
bgw_1.Eth2/9 --- Eth1/1.edge router
bgw_2.Eth2/9 --- Eth1/2.edge router
```

#### Switch Roles

- edge router is an Edge Router role
- bgw_1 is a Border role
- bgw_2 is a Border role

This test was running with no errors  with a different topology where bgw_1 and bgw_2 were both Border Gateway Spine role.
