### ISSUE TITLE
Support Port-channel sub-interface

### ISSUE THREAD

**Issue by ccoueffe** [CiscoDevNet/ansible-dcnm#358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, we can create Ethernet SubInterfaces and Port-Channel interfaces but not combined to have Port-Channel Sub-Interfaces.

### New or Affected modules(s):

* dcnm_interface

### DCNM version

* V 12.2.2

### Potential ansible task config

```yaml
   - name: Test subIf
      cisco.dcnm.dcnm_interface:
        fabric: nac-ndfc2
        deploy: true
        state: merged
        config:
          - name : Po10.1
            type: sub_int
            switch:
              - 10.229.42.211
            deploy: false
            profile:
              admin_state: True
              mode: 'subint'
              ipv4_addr: 192.168.111.1
              ipv4_mask_len: 30
              vlan: 3000
              description: NetAsCode Routed Sub Interface
              int_vrf: NaC-VRF21
              speed: auto
```

### References

**Additional context**
