### ISSUE TITLE
dcnm_inventory: Use of unpublished NDFC endpoints

### ISSUE THREAD

**Issue by allenrobel** [CiscoDevNet/ansible-dcnm#389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### DCNM version

* V 3.7.0

### Affected module(s)

* dcnm_inventory

### Ansible Playbook

```yaml
-   hosts: ndfc
    check_mode: false
    gather_facts: false
    vars:
        fabric_name: F1
        switch1: 10.1.1.2
        switch_username: admin
        switch_password: mypassword
    tasks:
    - name: Query switches in the fabric
      cisco.dcnm.dcnm_inventory:
        fabric: "{{ fabric_name }}"
        state: query
        config:
        - seed_ip: "{{ switch1 }}"
          role: spine
      register: result
    - debug:
        var: result
```

### Expected Behavior

The ansible-dcnm collection should, ideally, use only published endpoints.  The reasoning is that unpublished endpoints could be removed at any time, whereas published endpoints would be deprecated and removed only after a period of time provided in a deprecation notice in the Nexus Dashboard release-notes.

Unpublished endpoints found thus far:

1. GET /appcenter/cisco/ndfc/api/about/version 

A published alternative with the same output is:
 
- GET /appcenter/cisco/ndfc/api/v1/fm/about/version

2. GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{fabric_name}/inventory

A published alternative (different output, but should be relatively easy to incorporate)

- GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{fabric_name}}/inventory/switchesByFabric 

3. GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/lanConfig/getLanSwitchCredentials

A published alternative with the same output is:

- GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/lanConfig/getLanSwitchCredentialsWithType

4. PUT /fm/fmrest/topology/role/{switchDbId}?newRole=leaf

A published alternative might be:

- POST /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/switches/roles

### Actual Behavior

Unpublished endpoints are used, as described above.

### Steps to Reproduce

Run the attached playbook.
