### ISSUE TITLE
Short Name example needs to be updated

### ISSUE THREAD

**Issue by mipetrin** [CiscoDevNet/ansible-dcnm#4]
In the example for adding the collection to then use the short name, the task needs to be updated to only use the short name

Example in README section:

```
---
- hosts: dcnm_hosts
  gather_facts: false
  connection: httpapi

  collections:
    - cisco.dcnm

  tasks:
    - name: Merge a Switch
      cisco.dcnm.dcnm_inventory:
        ...parameters...
```

cisco.dcnm.dcnm_inventory should be shortened to dcnm_inventory:
