### ISSUE TITLE
DCNM vPC Pair Module does not work on External fabric

### ISSUE THREAD

**Issue by peter8498** [CiscoDevNet/ansible-dcnm#422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

2.16.3

### DCNM version

12.2.3

### Affected module(s)

cisco.dcnm.dcnm_vpc_pair

### Ansible Playbook

```yaml
      - name: Merge VPC switch pair paremeters
        cisco.dcnm.dcnm_vpc_pair:
          src_fabric: "TEST-SVS-SL1"
          deploy: false
          state: merged
          config:
            - peerOneId: FDO2729038J
              peerTwoId: FDO27290391
              templateName: "vpc_pair"
              profile:
                ADMIN_STATE: True
                ALLOWED_VLANS: "all"
                DOMAIN_ID: 11
                FABRIC_NAME: TEST-SVS-SL1
                KEEP_ALIVE_HOLD_TIMEOUT: 3
                KEEP_ALIVE_VRF: management
                PC_MODE: active
                PEER1_DOMAIN_CONF: ""
                PEER1_KEEP_ALIVE_LOCAL_IP: 10.1.150.100
                PEER1_MEMBER_INTERFACES: e1/15,e1/16
                PEER1_PCID: 500
                PEER1_PO_CONF: "buffer-boost"
                PEER1_PO_DESC: "This is peer1 PC"
                PEER2_DOMAIN_CONF: ""
                PEER2_KEEP_ALIVE_LOCAL_IP: 10.1.150.101
                PEER2_MEMBER_INTERFACES: e1/15,e1/16
                PEER2_PCID: 500
                PEER2_PO_CONF: "buffer-boost"
                PEER2_PO_DESC: "This is peer2 PC"
```

### Debug Output

The full traceback is:
Traceback (most recent call last):
  File "/home/auto-user/.ansible/tmp/ansible-local-19789173qo7w29c/ansible-tmp-1748863609.5408928-1978969-171551319852259/AnsiballZ_dcnm_vpc_pair.py", line 107, in <module>
    _ansiballz_main()
  File "/home/auto-user/.ansible/tmp/ansible-local-19789173qo7w29c/ansible-tmp-1748863609.5408928-1978969-171551319852259/AnsiballZ_dcnm_vpc_pair.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/auto-user/.ansible/tmp/ansible-local-19789173qo7w29c/ansible-tmp-1748863609.5408928-1978969-171551319852259/AnsiballZ_dcnm_vpc_pair.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.dcnm.plugins.modules.dcnm_vpc_pair', init_globals=dict(_module_fqn='ansible_collections.cisco.dcnm.plugins.modules.dcnm_vpc_pair', _modlib_path=modlib_path),
  File "/home/auto-user/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/auto-user/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/auto-user/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py", line 1305, in <module>
  File "/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py", line 1249, in main
  File "/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py", line 988, in dcnm_vpc_pair_validate_all_input
  File "/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py", line 934, in dcnm_vpc_pair_validate_input
  File "/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/module_utils/network/dcnm/dcnm.py", line 757, in dcnm_get_template_specs
KeyError: 'ipAddress'
fatal: [fed-svs-vxlan]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/auto-user/.ansible/tmp/ansible-local-19789173qo7w29c/ansible-tmp-1748863609.5408928-1978969-171551319852259/AnsiballZ_dcnm_vpc_pair.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/auto-user/.ansible/tmp/ansible-local-19789173qo7w29c/ansible-tmp-1748863609.5408928-1978969-171551319852259/AnsiballZ_dcnm_vpc_pair.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/auto-user/.ansible/tmp/ansible-local-19789173qo7w29c/ansible-tmp-1748863609.5408928-1978969-171551319852259/AnsiballZ_dcnm_vpc_pair.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.dcnm.plugins.modules.dcnm_vpc_pair', init_globals=dict(_module_fqn='ansible_collections.cisco.dcnm.plugins.modules.dcnm_vpc_pair', _modlib_path=modlib_path),\n  File \"/home/auto-user/.pyenv/versions/3.10.13/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/home/auto-user/.pyenv/versions/3.10.13/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/home/auto-user/.pyenv/versions/3.10.13/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py\", line 1305, in <module>\n  File \"/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py\", line 1249, in main\n  File \"/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py\", line 988, in dcnm_vpc_pair_validate_all_input\n  File \"/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/modules/dcnm_vpc_pair.py\", line 934, in dcnm_vpc_pair_validate_input\n  File \"/tmp/ansible_cisco.dcnm.dcnm_vpc_pair_payload_7o9s47zc/ansible_cisco.dcnm.dcnm_vpc_pair_payload.zip/ansible_collections/cisco/dcnm/plugins/module_utils/network/dcnm/dcnm.py\", line 757, in dcnm_get_template_specs\nKeyError: 'ipAddress'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *******************************************************************************************************************************************************
fed-svs-vxlan              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

### Expected Behavior

The VPC Pair module should accpet this as i've taken the example straight out of the documentation for the module and just changed the IP/Serials to match my setup

### Actual Behavior

Fails with the above error

### Steps to Reproduce

Run the given playbook and try and create a vpc Pair on an external fabric using the vpc_pair template as per the GUI
