### ISSUE TITLE
Add control options for enabling CDP/PFC and Monitor mode on physical interfaces (access/trunk) and non-vpc port-channels (access/trunk)

### ISSUE THREAD

**Issue by mkilar123** [CiscoDevNet/ansible-dcnm#430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible [core 2.16.3]
  config file = None
  configured module search path = ['/Users/mkilar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/mkilar/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.12/bin/ansible
  python version = 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)] (/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12)
  jinja version = 3.1.5
  libyaml = True

### DCNM version

NDFC 12.2.2

### Affected module(s)

* dcnm_interface

### Ansible Playbook

```yaml
---
vxlan:
  fabric:
    name: VAC_FAB1
    type: VXLAN_EVPN
  global:
    bgp_asn: "2.65010"

  topology:
    switches:
      - name: VAC_SPINE11
        serial_number: 9BUXESV382R
        role: border_gateway_spine
        management:
          default_gateway_v4: 198.18.133.1
          management_ipv4_address: 198.18.133.11
        routing_loopback_id: 0
        vtep_loopback_id: 1
      - name: VAC_LEAF15
        serial_number: 925RKAV24KC
        role: leaf
        management:
          default_gateway_v4: 198.18.133.1
          management_ipv4_address: 198.18.133.15
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: e1/5
            mode: access
            description: "mkilar_description"
            enabled: true
            access_vlan: 17
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            enable_cdp: true
            enable_pfc: false
            enable_monitor: true
          - name: e1/6
            mode: trunk
            description: "mkilar_description"
            enabled: true
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            enable_cdp: true
            enable_pfc: false
            enable_monitor: true
          - name: port-channel7
            mode: trunk
            description: "mkilar_description"
            enabled: true
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            enable_cdp: true
            enable_pfc: false
            enable_monitor: true
            members:
              - eth1/7
          - name: port-channel8
            mode: access
            description: "mkilar_description"
            enabled: true
            access_vlan: 17
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            enable_cdp: true
            enable_pfc: false
            enable_monitor: true
            members:
              - eth1/8
```

### Debug Output
N/A

### Expected Behavior
I would be great if the dcnm_module would reflect the cababilities / config options offered by the NDFC GUI.
At this point in time - among others - the module doesn't allow to control the enablement of CDP (cisco discovery protocol), PFC (priority flow control) and Monitor mode.

### References
N/A
