### ISSUE TITLE
Add support for BGP fabric type into dcnm_fabric module

### ISSUE THREAD

**Issue by mkilar123** [CiscoDevNet/ansible-dcnm#432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At this point in time the DCNM_FABRIC module doesn't support the BGP Fabric type.
This the fabric which uses BGP as the underlay routing protocol and can optionally have EVPN enabled on top.

### New or Affected modules(s):

* dcnm_fabric

### DCNM version

* cisco.dcnm :: 3.8.0-dev
* NDFC :: 12.2.2

### Potential ansible task config

```yaml
- hosts: BGP_FAB1
  any_errors_fatal: true
  gather_facts: no
  collections:
    - cisco.dcnm
  
  tasks:
    - name: Create BGP Fabric
      cisco.dcnm.dcnm_fabric:
        state: merged
        config:
        -   FABRIC_NAME: BGP_FAB1
            FABRIC_TYPE: BGP
            BGP_AS: 65001
            SUPER_SPINE_BGP_AS: 65002
            DEPLOY: false
      register: result
    - debug:
        var: result
```

### References

**Additional context**
