### ISSUE TITLE
Add Fabric Type: External Connectivity Network

### ISSUE THREAD

**Issue by aj-cruz** [CiscoDevNet/ansible-dcnm#440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unless I'm missing something there's no way to create a fabric type of **External Connectivity Network**

### New or Affected modules(s):

* dcnm_fabric

### DCNM version

* V 12.2.2.241

### Potential ansible task config

```yaml
- name: Merge External Connectivity Network fabric
  cisco.dcnm.dcnm_fabric:
    state: merged
    config:
    -   FABRIC_NAME: EXT-FABRIC
        FABRIC_TYPE: EXT
        BGP_AS: 65001
```

### References

**Additional context**
