### ISSUE TITLE
Setting deploy to false still pushes the configuration to the switch

### ISSUE THREAD

**Issue by micruzz82** [CiscoDevNet/ansible-dcnm#57]
I am trying to ensure that anytime I configure DCNM policies on the switch, I would like to manually re-validate the configuration on all switches before running the save and deploy.

Following is my playbook.

```
--- 
- 
  connection: ansible.netcommon.httpapi
  gather_facts: false
  hosts: dcnm
  tasks: 
    - 
      cisco.dcnm.dcnm_policy: 
        config: 
          - 
            #deploy: false
            #state: merged
            switch: 
              - 
                ip: "{{ ansible_switch1 }}"
                policies: 
                  - 
                    create_additional_policy: false
                    name: feature_bfd
            deploy: false
            state: merged
        fabric: "{{ ansible_it_fabric }}"
      name: "Create different policies"
      no_log: false
      vars: 
        ansible_command_timeout: 1000
        ansible_connect_timeout: 1000
  vars: 
    ansible_it_fabric: dcnm-fabric
    ansible_switch1: "10.1.1.1"
    ansible_switch2: "10.1.1.2"

```
==========================================

I have tried false and I have tried no. 

ansible-galaxy collection list | grep dcnm
cisco.dcnm        1.1.0

ansible --version
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]

Would you be able to advise if this is a bug in the latest version please?

**Comment by micruzz82** [comment]
It would be good if you set the global default to false rather than true. This way a user is explicitly stating they want to push the config from the code.

**Comment by mikewiebe** [comment]
@micruzz82 Thanks for opening the issue.  We are working on a fix.  Thanks!

**Comment by mikewiebe** [comment]
@micruzz82 I was able to figure out what is happening.  You probably cut and pasted your first `dcnm_policy` task from our example documentation but there is a problem with the indentation in the docs.

The `deploy:` flag and `state:` flags need to be at the the `config:` parameter.

For example, the following is valid:

```yaml
    - name: Create policy
      cisco.dcnm.dcnm_policy:
        fabric: "{{ fabric_name }}"
        state: merged
        deploy: true
        config:
          - name: wiebe55  # This must be a valid template name
            create_additional_policy: false  # Do not create a policy if it already exists
            priority: 101

          - switch:
              - ip: "{{ leaf1 }}"

```

But the following is not valid and the `deploy` and `merge` flags will be ignored since they are children of `config:` in this context.  This is a bug that we need to fix but for now, just make sure the indentation for the `deploy:` and `state:` parameters are at the same indentation level as `config:`

```yaml
    - name: Create policy
      cisco.dcnm.dcnm_policy:
        fabric: "{{ fabric_name }}"
        config:
          - name: wiebe55  # This must be a valid template name
            create_additional_policy: false  # Do not create a policy if it already exists
            priority: 101

          - switch:
              - ip: "{{ leaf1 }}"
        deploy: false
        state: merged
```

We will fix the documentation and generate a user error if they `deploy:` and `state:` parameters are under config.
