### ISSUE TITLE
Timeout triggered when adding many interfaces

### ISSUE THREAD

**Issue by tias77** [CiscoDevNet/ansible-dcnm#58]
Creating one or two vPC interfaces is no problem.
Adding 40+ seems to be working looking at interfaces in DCNM webui, but ansible triggers timeout.
Rerunning the same task works fine.
I'll add more data as I find it.

**Comment by tias77** [comment]
I see no effect using:
```
[persistent_connection]
connect_timeout = 480
command_timeout = 480
```
in ansible.cfg

**Comment by mikewiebe** [comment]
@tias77 Thanks for opening the issue.  We are investigating and will reply back soon.

**Comment by tias77** [comment]
Sure, here's my playbook:
```
---

- hosts: dcnm_controllers
  gather_facts: false
  connection: ansible.netcommon.httpapi

  tasks:
    - name: Create vPC interfaces
      cisco.dcnm.dcnm_interface: &vpc_merge
        fabric: fabric1
        state: replaced                         # only choose from [merged, replaced, deleted, overridden, query]
        config:
          - name: vpc1
            type: vpc
            switch:
              - "le1"
              - "le3"
            deploy: true                       # choose from [true, false]
            profile:
              admin_state: true                ## choose from [true, false]
              mode: trunk                      # choose from [trunk, access]
              peer1_members:                   ## member interfaces on peer 1
                - e1/1
              peer2_members:                   ## member interfaces on peer 2
                - e1/1
              pc_mode: 'active'                ## choose from ['on', 'active', 'passive']
              bpdu_guard: true                 ## choose from [true, false, 'no']
              port_type_fast: true             ## choose from [true, false]
              mtu: jumbo                       ## choose from [default, jumbo]
              peer1_description: "VPC acting as trunk peer1 - modified"
              peer2_description: "VPC acting as trunk peer2 - modified"
```
and then repeat that for all 48 interfaces
