### ISSUE TITLE
Ansible playbook for adding policy template with argument values does not get configured on DCNM

### ISSUE THREAD

**Issue by micruzz82** [CiscoDevNet/ansible-dcnm#60]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]

ansible-galaxy collection list | grep dcnm
cisco.dcnm        1.1.0 

### DCNM version

* V 11.5.1

### Affected module(s)

* cisco.dcnm.dcnm_policy

### Ansible Playbook

```yaml
---

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_it_fabric: dcnm-fabric
    ansible_switch1: 10.20.20.1
    ansible_switch2: 10.20.20.2

  tasks:
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: false
        state: merged
        config:
          - name: add_ip_prefix_list              # This must be a valid template name
            create_additional_policy: false  # Do not create a policy if it already exists
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list
              ACL_NAME: 10.122.84.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit

    
          - switch:
              - ip: "{{ ansible_switch1 }}"

      vars:
          ansible_command_timeout: 1000
          ansible_connect_timeout: 1000
```

### Debug Output

https://gist.github.com/micruzz82/15a0992561c4584f8b962abe2305b32a

### Expected Behavior

![image](https://user-images.githubusercontent.com/24628054/115591869-7e3db980-a2ca-11eb-8c22-efb4da356e3d.png)

This is the new custom template created in the template library.

policy template is for device.

Following are the variables for template policy  "add_ip_prefix_list"

                        "ACL_NAME": "10.122.84.0/24",
                        "PREFIX_LIST_ACTION": "permit",
                        "PREFIX_LIST_NAME": "ansible-prefix-list",
                        "SEQ_NUM": 20

As per documentation example, once the playbook is run, it should have updated a new policy on the switch.

### Actual Behavior

The playbook just runs without any errors and nothing is configured on DCNM for the switch that needs to be configured.

### Steps to Reproduce

Step 1)
Create a new template in template library: "add_ip_prefix_list"

Add following to template:

##template variables

@(DisplayName="Prefix List Name", Description="Name of Prefix List with max. 63 characters, example PL-ICE-")
string PREFIX_LIST_NAME {
    maxLength = 63;
};

@(DisplayName="Prefix List Action", Description="Prefix List permit or deny operation")
enum PREFIX_LIST_ACTION {
    validValues=permit,deny;
    defaultValue=permit;
};

@(DisplayName="Prefix List Sequence Number", Description="Prefix List match sequence number, example 10")
integer SEQ_NUM {
    min = 0;
    max = 65535;
    defaultValue=10;
};

@(DisplayName="ACL Name", Description="Name of ACL with max. 63 characters, example 10.x.x.x/x or 10.x.x.x/x le xx")
string ACL_NAME {
    maxLength = 63;
};

##
##template content

ip prefix-list $$PREFIX_LIST_NAME$$ seq $$SEQ_NUM$$ $$PREFIX_LIST_ACTION$$ $$ACL_NAME$$
  
##

Step 2)
configure ansible playbook for fabric as documented above.

Step3) 
Execute playbook to verify if policy has been updated on switch.

**Comment by micruzz82** [comment]
Looking back I see this:
"skipped": [
                {
                    "Reason": "Trying to modify Policy using Template Name, use policy ID",
                    "Template": "add_ip_prefix_list"
                }

**Comment by mikewiebe** [comment]
@micruzz82 We are currently discussing this issue and originally we did consider adding the `policy_id` option but decided against it since the workflow would remain essentially the same.

* Step 1: Create a policy using the template name: 
    * This will create a policy and return the policy number
    * If `deploy` is `true` the policy will be created and applied to the switch
    * If `deploy` is `false` the policy will be created but not applied to the switch

```yaml
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: false                    <------------------ Set to false initially
        state: merged
        config:
          - name: add_ip_prefix_list             <------------------ Template Name
            create_additional_policy: false
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list
              ACL_NAME: 10.122.84.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit


          - switch:
              - ip: "{{ ansible_switch1 }}"
      register: result
```

* Step 2: Apply the policy to the device **(Not needed if the `deploy` flag was set to `true` in Step 1)**

```yaml
    - name: Apply policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: true                     <------------------ Set to true when using policy name
        state: merged
        config:
          - name: POLICY-3170750             <------------------ Auto Generated Policy Name
            create_additional_policy: false
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list
              ACL_NAME: 10.122.84.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit


          - switch:
              - ip: "{{ ansible_switch1 }}"
      register: result
```

If we added the extra `policy_id:` parameter this same workflow would still be required since the policy numbers get auto-generated by DCNM

The difference is that in Step1, only `name` would be used and in Step2 `name` and `policy_id` would be used but `name` would essentially be ignored.

**Comment by mikewiebe** [comment]
@micruzz82  I tested the workflow with your custom policy and it's working for me and applying the config to the switch as long as I either set the deploy flag to `true` in step1 or replace the template name with the auto-generated policy id in step 2.  Is that workflow working for you?

**Comment by micruzz82** [comment]
Thanks for this @mikewiebe maybe to explain my reasoning why I would prefer to only deploy the intent to the switches but not push the config. Basically as we have maintenance windows, it would be good to have the CI/CD run but we deploy the config from DCNM to ensure we cover all the bases. Only because I want to avoid having the automation push the final go button. I know a bit counter-intuitive but it's more of a trust exercise at this stage since this is the first deployment where we want to transition into the new world of the devops culture. I'm learning as I go along and while we can indeed simulate in the lab etc but a lab doesn't always represent a production environment so we want to ensure we keep that last push a manual push at this stage till we have things under control. I'll test this out now and report back how this comes out from testing. Thank you once again for your quick support. I do appreciate all the time and effort you are spending to help me on this. This playbook is the last playbook which I need to work out but once I understand it, that should be all I need to start working on the automated deployment. Thanks again and will report back.

**Comment by micruzz82** [comment]
I have tried the same as what you have above but I still get the same result. Would you be able to please send me your full yaml file as I'm not sure what else I need to change.

```
"skipped": [
                {
                    "Reason": "Trying to modify Policy using Template Name, use policy ID",
                    "Template": "add_ip_prefix_list"
                }
```

**Comment by micruzz82** [comment]
Right I think I understand this a bit more. If you are adding a template which has never been used before the deploy false works and it will push the policy to the switch correctly.

However in my use case, I want to create different policies but use the same template.

For example, I can have route map RM-1 and RM-2

RM-1 can use ACL-1 and RM-2 can use ACL-2

However with my template, when I specify manually, it can create the different policies as I need it.

But if I use it with the ansible module you have, I can only create and use a template once which means, I will have quite a lot of templates to keep track of which is not what would be the best way for this.

So I think we would need to come up with a way to dynamically generate the policy ID at runtime and try and make use of the same template multiple times where I can dynamically change the ACL name.

Hope the above made sense.

**Comment by micruzz82** [comment]
Following is what I currently have:

![image](https://user-images.githubusercontent.com/24628054/115799570-b2030700-a3d0-11eb-8fc8-5d1197630013.png)

I have even try to set create additional policy true

```
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: false                    #<------------------ Set to false initially
        state: merged
        config:
          - name: add_ip_prefix_list            # <------------------ Template Name
            create_additional_policy: true       # <------------------ Set to true
            priority: 500
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-2     # <------------------ new prefix list
              ACL_NAME: 10.122.85.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - switch:
              - ip: "{{ ansible_switch1 }}"
```

I still receive:

```
            "skipped": [
                {
                    "Reason": "Trying to modify Policy using Template Name, use policy ID",
                    "Template": "add_ip_prefix_list"
                }
            ]
        }
    ],
```

**Comment by micruzz82** [comment]
after a bit of though, I went thru the python code and added the following :)

            elif rc == "DCNM_POLICY_MERGE":
                # A policy exists and it needs to be updated
                # Merge is allowed only in the case of user providing policyId in place of templateName.
                # This is because there can be multiple policies with the same templateName and hence we
                # will not know which policy the user is referring to. In the case where a user is providing
                # a templateName and we are here, ignore the policy.             
                if policy.get("policyId", None) != None:
                    if policy not in self.diff_modify:
                        self.changed_dict[0]["merged"].append(policy)
                        self.diff_modify.append(policy)

###
                elif (policy.get("policyId", None) == None) and (policy["create_additional_policy"] == True):
                    if policy not in self.diff_modify:
                        self.changed_dict[0]["merged"].append(policy)
                        self.diff_create.append(policy)
###


Once I added this in I was able to get the desired outcome. I know this may not be what the code was intended to do but I think for what I want to achieve this works great. Please let me know if you can validate this internally to see if we can perhaps add some more guard rails to ensure only users who want to use this feature can enabled a custom flag true to add this as a feature.

**Comment by mikewiebe** [comment]
@micruzz82 I believe we can achieve what you want without making the modification to the code that you are suggesting above.

From reading your requirement above, you want to be able to use the same template but create multiple policies with different variable content for each policy. 

Here is the playbook task you can use for that:

```yaml
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: true
        state: merged
        config:
          - name: add_ip_prefix_list
            create_additional_policy: true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list
              ACL_NAME: 10.122.84.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - name: add_ip_prefix_list
            create_additional_policy: true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-2
              ACL_NAME: 10.122.85.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - name: add_ip_prefix_list
            create_additional_policy: true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-3
              ACL_NAME: 10.122.85.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
```

As you can see I have 3 items in my `config:` list that are using the same template `add_ip_prefix_list` but the key is you need to set the `create_additional_policy` flag to `true` to force a new policy to be created each time.

The `deploy` flag is set to `false` so it will create all 3 policies and deploy them in one step.

After running this task I see the following on my switch:

```shell
n9kv-leaf2# show run | inc ansible
ip prefix-list ansible-prefix-list seq 20 permit 10.122.84.0/24 
ip prefix-list ansible-prefix-list-2 seq 20 permit 10.122.85.0/24 
ip prefix-list ansible-prefix-list-3 seq 20 permit 10.122.85.0/24 
```

If you do this with the `deploy` flag set to `false` then all 3 polices will be created but then you would need a second task to reference the policy names to deploy them config to the switch.

Here is what the second task would look like:

```yaml
    - name: Apply policies to switches
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: true
        state: merged
        config:
          - name: POLICY-3248440
            create_additional_policy: false
          - name: POLICY-3248450
            create_additional_policy: false
          - name: POLICY-3248460
            create_additional_policy: false
```

In this case you set the `deploy` flag to `true` to apply the 3 policies created in the first task but make sure in this case to set the `create_additional_policy` to `false`.

**Comment by micruzz82** [comment]
Hi @mikewiebe thanks again .. but again as I already have the same template configured, I still get thrown the error:
```
            "skipped": [
                {
                    "Reason": "Trying to modify Policy using Template Name, use policy ID",
                    "Template": "add_ip_prefix_list"
                },
                {
                    "Reason": "Trying to modify Policy using Template Name, use policy ID",
                    "Template": "add_ip_prefix_list"
                },
                {
                    "Reason": "Trying to modify Policy using Template Name, use policy ID",
                    "Template": "add_ip_prefix_list"
                }
            ]
        }
    ],
```

I think I will stick with the additional 4 lines of code that I can add to the configuration as it's a single playbook I can then use rather than have to do 3-4 separate tasks to achieve the same result. I've taken up enough of your time on this as I'm sure you have other priority things to work on...so as I've found a workaround to my problem I'll close this issue since you'd prefer to keep your code as a stable release.

This was the last issue that was blocking me but now that I have a workaround in place.. I'll keep this under control so only certain members of the team will run this specific playbook. Much appreciated for your time and support to help me to understand this module. I'll work to try and get it working following the orginal python code but as I've got some timelines to meet for delivery will use what I have to get things moving.

If you're able to consider adding the condition into the main branch after extra checks that would be a massive help since it will simplify the playbook quite a lot and with very few changes to variables.

**Comment by mikewiebe** [comment]
@micruzz82 I don't mind spending the time because I agree with you that your workflow is the desired behavior.  You absolutely should be able to use the same template name to create multiple policies and then use those policies on your switch.  I am not seeing the same behavior you are seeing.  I can create new policies with the same template name just fine and don't get the skipped message.  Trying to understand the delta between your environment and ours.

If you have this issue others will have it so planning to get to the bottom of it and if we need to add your code or some variant of it we will :)

**Comment by micruzz82** [comment]
that's great @mikewiebe I'm using exactly the same playbook I have pasted above. so yeah even I'm stumped as to why it works for you and not for me. I've pasted the ansible  version as well so not sure if that could be a factor.

Thanks once again and I do hope that we can add the condition in to make life easier and we can work thru a common master branch and not break away from the main code.

**Comment by micruzz82** [comment]
ah one thing to add. I use tacacs authentication with my login to DCNM.. so not use if it's an issue with tacacs rather than local admin login?

**Comment by micruzz82** [comment]
Ah one more thing I noticed. You are using virtual 9K switches while I'm using actual physical switches. So maybe that could be the reason as well @mikewiebe

**Comment by mikewiebe** [comment]
@micruzz82 I was able to recreate the skipped message you are seeing by running the task again on my switch (as you suggested) **BUT...** that would not stop the second task from executing.

Here is the workflow:

* Run task1 for the first time (this generates 3 new policies based on the template)
* Run task2 using the new policies created in task1 to apply the policies to the device.
* Run  task1 and task2 again:
    * task1 will generate the skipped message because the policies have already been created.
    * task2 will still run and apply the policies to the device.

Now, if you want to add a new policy (policy 4) to task1, there is an issue.  Even the new policy will be skipped so we probably have a bug there.

I patched in your suggested change and it does create new policies every time task1 is run but the problem is that you will get new policies every time you run task1.  

For example, if you run task1 six times you will get 3x6 for a total of 18 policies.  If you run it six more times you will get 18 more policies so I don't think that is what you want...

**Comment by micruzz82** [comment]
Yes I noticed the same behaviour as well I wanted to inform but as we were not able to replicate didnt' want to push that forward just yet till we could recreate the issues.

But I do agree that there is scope to amend this module so we can get the best of both worlds until a proper fix is in place. For the moment I will run the playbook as you have suggested and I will wait for an official fix whenever it comes out. much appreciated for seeing this through.

**Comment by micruzz82** [comment]
I also wanted to add, is there anyway to get a list of policies in pending state to perform another validation to ensure that you can check the new policy against an existing policy that is waiting to be deployed. Kind of something like this but for policies in pending state:

```
    def dcnm_policy_compare_policies(self, policy):

        found = False
        match_pol = []

        if self.have == []:
            return ("DCNM_POLICY_ADD_NEW", None)

        # For modify cases, we need to match the exact policy and so we should compare
        # policyIds. For create cases use templateName key.

        if policy.get("policyId", None) != None:
            key = "policyId"
        else:
            key = "templateName"

        for have in self.have:
            if have[key] == policy[key]:
                found = True
                # Have a policy with matching template name. Check for other objects
                if have.get("description", None) == policy["description"]:
                    if have.get("priority", None) == policy["priority"]:
                        if (
                            have.get("serialNumber", None)
                            == policy["serialNumber"]
                        ):
                            if (
                                self.dcnm_policy_compare_nvpairs(
                                    policy.get("nvPairs", None),
                                    have.get("nvPairs", None),
                                )
                                == "DCNM_POLICY_MATCH"
                            ):
                                return (
                                    "DCNM_POLICY_DONT_ADD",
                                    have["policyId"],
                                )
        if found == True:
            # Found a matching policy with the given template name, but other objects don't match.
            # Go ahead and merge the objects into the existing policy
            return ("DCNM_POLICY_MERGE", have["policyId"])
        else:
            return ("DCNM_POLICY_ADD_NEW", None)
```

**Comment by mikewiebe** [comment]
@micruzz82 The module has a state `query` that will allow you to get a list of all policies in any state for that particular template name.  Does that data return what you need?  Are you trying to use the data in a subsequent task in your playbook before you deploy the policies?

**Comment by micruzz82** [comment]
hi @mikewiebe yes that's correct.

Basically I wanted to modify the condition once it enters this section:
###
   elif (policy.get("policyId", None) == None) and (policy["create_additional_policy"] == True):
                if policy not in self.diff_modify:
                    self.changed_dict[0]["merged"].append(policy)
                    self.diff_create.append(policy)
###

when it hits this elif condition, it should compare the policies that are requested to be configured against the list of all policies, pending and configured, and if a match is found, then skip the task. If a match is not found then it should go ahead and create the policy.

I was trying to find ways to see how to match condition with:

###
 for have in self.have:
            if have[key] == policy[key]:
                found = True
                # Have a policy with matching template name. Check for other objects
                if have.get("description", None) == policy["description"]:
                    if have.get("priority", None) == policy["priority"]:
                        if (
                            have.get("serialNumber", None)
                            == policy["serialNumber"]
                        ):
                            if (
                                self.dcnm_policy_compare_nvpairs(
                                    policy.get("nvPairs", None),
                                    have.get("nvPairs", None),
                                )
                                == "DCNM_POLICY_MATCH"
                            ):
                                return (
                                    "DCNM_POLICY_DONT_ADD",
                                    have["policyId"],
                                )
###

but every attempt I made, I was never able to get a return of DCNM_POLICY_DONT_ADD.

So wasn't sure if a fix would be provided from your side now that you are able to replicate the scenario?

**Comment by micruzz82** [comment]
For reference, this is what I tried to do:

(I must stress that programming is not really my strong suite but I am trying to follow the logic to see if this can perhaps help me with my use case)

```
    def new_dcnm_policy_compare_policies(self, policy):

        found = False
        match_pol = []

        if self.have == []:
            return ("DCNM_POLICY_ADD_NEW", None)

        # For modify cases, we need to match the exact policy and so we should compare
        # policyIds. For create cases use templateName key.

        if policy.get("policyId", None) != None:
            key = "policyId"
        else:
            key = "templateName"

        for have in self.have:
            if have[key] == policy[key]:
                # Have a policy with matching template name. Check for other objects
                if have.get("description", None) == policy["description"]:
                    if have.get("priority", None) == policy["priority"]:
                        if ( have.get("serialNumber", None)== policy["serialNumber"] ):
                            if (self.dcnm_policy_compare_nvpairs(policy.get("nvPairs", None),have.get("nvPairs", None),) == "DCNM_POLICY_MATCH"):
                                found = True
        if found == True:
            # Found a matching policy with the given template name, but other objects don't match.
            # Go ahead and merge the objects into the existing policy
            return ("DCNM_POLICY_DONT_MERGE", have["policyId"])
        else:
            return ("DCNM_POLICY_MERGE", None)


                elif (policy.get("policyId", None) == None) and (policy["create_additional_policy"] == True):
                    x,y = self.new_dcnm_policy_compare_policies(policy)
                    if x == "DCNM_POLICY_DONT_MERGE":
                        self.changed_dict[0]["skipped"].append(
                            {
                                "Template": policy["templateName"],
                                "Reason": "Trying to modify Policy using Template Name, use policy ID",
                            }
                        )
                        policy_id = None
                        continue
                    else:
                        if policy not in self.diff_modify:
                            self.changed_dict[0]["merged"].append(policy)
                            self.diff_create.append(policy)

```

**Comment by mikewiebe** [comment]
@micruzz82 Yes, we are working on a fix for this now that we can recreate the problem and this is the section of code that we are working to modify.

After discussion with our team today we decided on the following.

Each time a task is run that uses a template name and the `create_additional_policy` flag is `true`:

* Compare each existing policy (pending and configured) for a template name against the playbook list and create a new policy if it does not exist.
* If the policy does exist, don't create a new policy for it.
    * We have discussed using the `description` and `key/value` fields if they exist for a template to compare and determine if the policy already exists or not.

**Comment by micruzz82** [comment]
That's great news indeed! thanks very much for this. It will help me quite a lot and I'm sure other users too once this is integrated into the next release. Much appreciated for the efforts on this.

**Comment by mikewiebe** [comment]
@micruzz82 Thanks for working on some potential fixes and providing your source code.  Nice to see this level of collaboration! :) https://github.com/CiscoDevNet/ansible-dcnm/issues/60#issuecomment-827676493

This is certainly the right approach to solving the issue.

**Comment by micruzz82** [comment]
indeed. Thinking more on the above, I think it would be best to ignore these 2 lines:

```
                if have.get("description", None) == policy["description"]:
                    if have.get("priority", None) == policy["priority"]:
```
This is because you can't always guarantee that the priority or the description will exactly match and may result in a false positive that the policy does not exist.

**Comment by mikewiebe** [comment]
> indeed. Thinking more on the above, I think it would be best to ignore these 2 lines:
> 
> ```
>                 if have.get("description", None) == policy["description"]:
>                     if have.get("priority", None) == policy["priority"]:
> ```
> 
> This is because you can't always guarantee that the priority or the description will exactly match and may result in a false positive that the policy does not exist.

The challenge we have is that if the policy does not have any key/value pairs than `description` and/or `priority` might be the only fields we can use for comparison to determine if the policy exists or not.  We are sill thinking through this but I don't think we would want to compare the contents of a free form policy since it could be any switch config which could pose problems.  If we use `description` and `priority` the playbook writer would have to ensure they are using the same `description` and `priority` to control if a new policy gets created or not but at least IMO it's a bit more deterministic.

**Comment by micruzz82** [comment]
great progress on this @mikewiebe. I was just curious to know would this fix be part of a minor Ansible galaxy update to 1.1.1? Don't suppose you would know some timelines on when this would be released. I have a project I'm working on as I may have mentioned and we're planning to start the deployment week 17th May. I was hoping if the fix was released as an update next week, I would have about 2 weeks or so to test before we head for live deployment. A tall order for sure but any help would be appreciated.

**Comment by mikewiebe** [comment]
@micruzz82 Thanks for reaching out.  We are planning a minor `1.1.1` update with this fix and a few others.  We are trying to fix https://github.com/CiscoDevNet/ansible-dcnm/issues/62 as part of this update so it will likely be next week before we update Galaxy at the earliest.

**Comment by micruzz82** [comment]
That's great news. I think it's a good fix to include as well, since it will also speed up with configuring templates through ansible as well so I look forward to the release next week as I'm finalizing the rest of the design this week for final prep work and this would align well in the planning to get as much automation in place for the new build. Great work by you and the rest of the team to resolve these issues.

**Comment by micruzz82** [comment]
hi @mikewiebe hope all's well. I just wanted to follow up to confirm if you release of `1.1.1` is still on track to release for early next week or you may need additional time for this please?

**Comment by mikewiebe** [comment]
@micruzz82 Our target right now is May 11th for the `1.1.1` release.  Thanks!

**Comment by micruzz82** [comment]
Great news and thanks again.

**Comment by micruzz82** [comment]
@mikewiebe @mmudigon thanks for the release on `1.1.1` however I have tested this just now and it still does to provide the intended behaviour.

Test run:

```
---

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_it_fabric: TEST-FABRIC
    ansible_switch1: 10.x.x.54
    ansible_switch2: 10.x.x.55

  tasks:
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: false                    #<------------------ Set to false initially
        state: merged
        config:
          - name: add_ip_prefix_list
            create_additional_policy: true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-17
              ACL_NAME: 10.122.83.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - switch:
              - ip: "{{ ansible_switch1 }}"
      vars:
          ansible_command_timeout: 1000
          ansible_connect_timeout: 1000
```

Only first run of the playbook succeeds.

Secondary runs to try and "break" this does not yield expected behavior.

You can try to keep the same variables as playbook above, but just change the ACL_NAME to 10.122.8.0/24 and re-run the playbook, you will see it does not give an error to say it's modifying existing policy.

Third run, with the same playbook, jsut change the PREFIX_LIST_NAME to ansible-prefix-list-18

The output does not push this to the switch.

following is the trace:
https://gist.github.com/micruzz82/5ae1a88618cee624db2f16de9ae9b073

Please let me know if you can replicate this issue on your side.

**Comment by micruzz82** [comment]
I've also just created a new playbook with new prefix name and subnet and any other subsequent runs doesn't work anymore.

**Comment by micruzz82** [comment]
That's right @mikewiebe  it should be easy to test his. If you re-run the same playbook and change the PREFIX_LIST_NAME to ansible-prefix-list-18.. you will see the same result as https://gist.github.com/micruzz82/5ae1a88618cee624db2f16de9ae9b073

**Comment by micruzz82** [comment]
I have also commited the change to the switches... and re-ran the playbook with the change in the prefix list name which does not push the new prefix list.

**Comment by micruzz82** [comment]
This is what I run.

Playbook run 1

```
---

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_it_fabric: EVPN-PROD-FABRIC-01
    ansible_switch1: 10.x.x.233
    ansible_switch2: 10.x.x.234

  tasks:
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: false                    #<------------------ Set to false
        state: merged
        config:
          - name: add_ip_prefix_list
            create_additional_policy: true                     #<------------------ Set to true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-19         #<------------------ Set to 19
              ACL_NAME: 10.122.81.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - switch:
              - ip: "{{ ansible_switch1 }}"
      vars:
          ansible_command_timeout: 1000
          ansible_connect_timeout: 1000

```

Output:
https://gist.github.com/micruzz82/26be8710df61b44b84765045773c17ef



Playbook run 2

```
```
---

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_it_fabric: EVPN-PROD-FABRIC-01
    ansible_switch1: 10.x,x.233
    ansible_switch2: 10.x.x.234

  tasks:
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: false                    #<------------------ Set to false
        state: merged
        config:
          - name: add_ip_prefix_list
            create_additional_policy: true                     #<------------------ Set to true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-20         #<------------------ Set to 20
              ACL_NAME: 10.122.81.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - switch:
              - ip: "{{ ansible_switch1 }}"
      vars:
          ansible_command_timeout: 1000
          ansible_connect_timeout: 1000

```


Output:
https://gist.github.com/micruzz82/53795ace2ea226ab0ac9a2fc77fecbb5

**Comment by micruzz82** [comment]
Do you re-run the playbook on the same switch or a different switch? If you try it on the same switch you should see the same behavior that I am seeing. As I'm running the new 1.1.1 and ansible 2.10.8

**Comment by mikewiebe** [comment]
> Do you re-run the playbook on the same switch or a different switch? If you try it on the same switch you should see the same behavior that I am seeing. As I'm running the new 1.1.1 and ansible 2.10.8

Yes, here is the output from 3 runs.  The same playbook each time and the only thing I change is the `PREFIX_LIST_NAME` each time.  It's all run against the same switch.

https://gist.github.com/mikewiebe/eff887801b27087b8c963f73dbabe6c2

**Comment by micruzz82** [comment]
I see the issue

This is playbook run 3 with deploy=true

```
---

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_it_fabric: DG1-EVPN-PROD-FABRIC-01
    ansible_switch1: 10.254.128.233
    ansible_switch2: 10.254.128.234

  tasks:
    - name: Create policy including required variables
      cisco.dcnm.dcnm_policy:
        fabric: "{{ ansible_it_fabric }}"
        deploy: true                    #<------------------ Set to true
        state: merged
        config:
          - name: add_ip_prefix_list
            create_additional_policy: true                     #<------------------ Set to true
            priority: 101
            policy_vars:
              PREFIX_LIST_NAME: ansible-prefix-list-20         #<------------------ Set to 19
              ACL_NAME: 10.122.81.0/24
              SEQ_NUM: 20
              PREFIX_LIST_ACTION: permit
          - switch:
              - ip: "{{ ansible_switch1 }}"
      vars:
          ansible_command_timeout: 1000
          ansible_connect_timeout: 1000

```

Output:
https://gist.github.com/micruzz82/8f565aa1b4fe1ec61ee7c74828d39b64

So in essence this playbook only works on multiple runs when you specify deploy: true

Could I ask if we could have multiple runs of the playbook and also have the use case for deploy: false

I would much prefer to not directly deploy this and keep a manual deploy available to us.
