### ISSUE TITLE
Role[border_gateway]is not a valid role

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#63]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

```
ansible 2.10.5
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/virtualenv/ansible/lib/python3.7/site-packages/ansible
  executable location = /root/virtualenv/ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```
### DCNM version

* V 11.5.1

### Affected module(s)

* dcnm_inventory

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here 
---
- name: add switches to fabric
  hosts: dcnm
  gather_facts: false
  collections:
    - cisco.dcnm
  tasks:
    - name: add switches to fabric
      dcnm_inventory:
        fabric: "{{ lab109_fabric_1.fabric }}"
        config:
          - seed_ip: 172.31.186.152
            user_name: admin
            password: xxxxx
            max_hops: 0
            role: border_gateway
            preserve_config: false

```

### Debug Output
https://gist.github.com/dsx1123/153690db572ff4fff9e3ed52ace027e9

checked the API call, the role used in API is actually "border gateway", however if set the role to this string, it will not pass the validation. Only tested border gateway but I suspect same issue could apply to all other multi-word role.

### Expected Behavior

Switch should be added to fabric as border gateway

### Actual Behavior

see debug output 

### Steps to Reproduce

execute playbook above to register switch to exsited fabric
