### ISSUE TITLE
vrf lite configuration does not honor the auto deploy both flag

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#65]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### DCNM version

* V 11.5.1

### Affected module(s)

* dcnm_vrf

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here 
---
- name: Configure external connectivity
  hosts: dcnm
  gather_facts: false
  vars_files:
    - vars.yml
  collections:
    - cisco.dcnm
  tasks:
    - name: external | attach vrf blue to border leaf {{ border[0].name }}
      dcnm_vrf:
        fabric: "{{ fabric }}"
        config:
          - vrf_name: blue
            attach:
              - ip_address: "{{ border[0].ip }}"
                vrf_lite:
                  - peer_vrf: blue
```
And vrf lite configuration of fabric is set as below:
![image](https://user-images.githubusercontent.com/3794076/116640792-3220f380-a920-11eb-8d60-47518941afc2.png)

### Debug Output

[debug output](https://gist.github.com/dsx1123/dc71e49f4764f2ebc11a9811af5c8706)

### Expected Behavior

external fabric that connected to border should also be deployed

### Actual Behavior

external fabric is not deployed
### Steps to Reproduce

1. set vrf lite setting of fabric as below
![image](https://user-images.githubusercontent.com/3794076/116640792-3220f380-a920-11eb-8d60-47518941afc2.png)
2. run the playbook
3. check the deployment result, the auto deploy is set to false which cause the external fabric is not deployed:
![image](https://user-images.githubusercontent.com/3794076/116640912-7f9d6080-a920-11eb-82d9-9df393f5f3ac.png)

### References
Checked the code, looks like we did not get auto deploy flag from fabric, but instead, it is set to false no matter what:
```python
                    vrflite_con['VRF_LITE_CONN'][0]['IPV6_NEIGHBOR']=a_l['neighbor_ipv6']
                    vrflite_con['VRF_LITE_CONN'][0]['AUTO_VRF_LITE_FLAG']='false'
                    vrflite_con['VRF_LITE_CONN'][0]['PEER_VRF_NAME']=a_l['peer_vrf']
```
