### ISSUE TITLE
Support additional switch role types in dcnm_inventory module

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/ansible-dcnm#77]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for adding switches to other types of fabrics, such as External Fabric (first priority) and LAN Classic (lesser priority).

Honestly, it seems a bit limiting that the dcnm_inventory module merged the switch discovery and role assignment APIs into a single module when there was no real requirement or dependency enforcing that behavior.  As a result, we get this limiting behavior where switches can't be added to DCNM solely because a role isn't in the validated input field.

Perhaps the correct approach to this feature request is simply to split the tasks into simply adding a switch to the fabric (dcnm_inventory) and assigning it a role (dcnm_role)?

### New or Affected modules(s):

* dcnm_inventory

### DCNM version

* V 11.5.1

### Potential ansible task config

```yaml
-name: Merge switch into fabric
    cisco.dcnm.dcnm_inventory:
      fabric: external-fabric
      state: merged
      config:
       - seed_ip: 192.168.0.1
         auth_proto: MD5
         user_name: switch_username
         password: switch_password
         max_hops: 0
         role: access                                  # Valid types:  access, ToR, aggregation, etc. etc.
         preserve_config: False
```

### References

None.

**Additional context**
