### ISSUE TITLE
Add SVI interface type to dcnm_interface

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/ansible-dcnm#78]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For non-VXLAN fabrics, the ability to create an SVI is crucial for building out traditional (or classical) ethernet architectures.

And, of course, support for optionally configuring HSRP on the SVI as well.

### New or Affected modules(s):

* dcnm_interface

### DCNM version

* V 11.5.1

### Potential ansible task config

```yaml
    - name: Create SVI VLAN10 on Host (Source of Truth)
      dcnm_interface:
        fabric: external-fabric
        state: replaced
        config:
          - name: vlan10
            type: svi
            switch: "core1"
            deploy: false
            profile:
              admin_state: true
              interface_vrf: default
              ip: 192.168.10.1
              netmask_length: 24
              mtu: jumbo
              routing_tag: 12345
              disable_ip_redirects: true
              description: "SVI for VLAN 10"
              hsrp:
                ip: 192.168.10.254
                group: 1
                version: 1
                priority: 100
                preempt: true
                virtual_mac: lee7.dead.beef
```

### References

None.

**Additional context**
