### ISSUE TITLE
Add support for creating VPC pair

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/ansible-dcnm#79]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Aside from spines in a VXLAN fabric, most other switch types (border gateways or leafs) are frequently added as a VPC pair.  There's support for adding switches to a fabric but no support for the next logical step: vpc pairing.

For VXLAN fabrics, the required information is very minimal:  namely, which two switches are going to be paired.  The remaining settings are derived from fabric settings.

For external fabrics, the domain configuration information is required (PKA, Peer link port channel, etc.).

The example below shows all the options for external fabrics but only the "ip" attribute would be required for VXLAN fabrics.  So, as a matter of software, you'd validate the inputs based on fabric type.

### New or Affected modules(s):

* dcnm_vpc_domain

### DCNM version

* V 11.5.1

### Potential ansible task config

```yaml
      dcnm_vpc_domain:
        fabric: "{{ local_fabric }}"
        state: merged
        deploy: false
        config:
          - ip: 10.60.66.231                        # switch management ip (for DCNM lookup)
            pka_ip: 10.60.66.231                    # optional: what PKA source IP to use
            pka_vrf: management                     # optional: provide if non-default
            peerlink_po_id: 1
            peerlink_members: eth1/53-54
            peerlink_description: Ansible created
            peerlink_allowed_vlans: all
          - ip: 10.60.66.232                        # switch management ip (for DCNM lookup)
            pka_ip: 10.60.66.232                    # optional: what PKA source IP to use
            pka_vrf: management                     # optional: provide if non-default
            peerlink_po_id: 1
            peerlink_members: eth1/53-54
            peerlink_description: Ansible created
            peerlink_allowed_vlans: all
```

### References

[DCNM 11.5 section on configuring vPC in external fabric](https://www.cisco.com/c/en/us/td/docs/dcn/dcnm/1151/configuration/lanfabric/cisco-dcnm-lanfabric-configuration-guide-1151/m_web_client_control.html?bookSearch=true#task_fqy_vc4_qhb)

**Additional context**

**Comment by micruzz82** [comment]
would this module also support day 0 provisioning of border leafs to be configured as vpc peers using vpc fabric peering?

**Comment by gve-vse-tim** [comment]
Adding a module level attribute boolean of "fabric_peering" would be a great add on. So an updated example would be:

```
      dcnm_vpc_domain:
        fabric: "{{ local_fabric }}"
        fabric_peering: false
        state: merged
        deploy: false
        config:
          - ip: 10.60.66.231                        # switch management ip (for DCNM lookup)
            pka_ip: 10.60.66.231                    # optional: what PKA source IP to use
            pka_vrf: management                     # optional: provide if non-default
            peerlink_po_id: 1
            peerlink_members: eth1/53-54
            peerlink_description: Ansible created
            peerlink_allowed_vlans: all
          - ip: 10.60.66.232                        # switch management ip (for DCNM lookup)
            pka_ip: 10.60.66.232                    # optional: what PKA source IP to use
            pka_vrf: management                     # optional: provide if non-default
            peerlink_po_id: 1
            peerlink_members: eth1/53-54
            peerlink_description: Ansible created
            peerlink_allowed_vlans: all

```
